import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const prototypeRoot = path.join(repoRoot, "apps/game/mahjong-roguelike/prototypes/config-playable");

describe("胡了卜配置试玩原型页面边界", () => {
  const playHtml = readFileSync(path.join(prototypeRoot, "index.html"), "utf8");

  it("默认入口是玩家试玩页，并把调牌器放到独立新窗口", () => {
    expect(playHtml).toContain('<body class="play-view" data-prototype-view="play">');
    expect(playHtml).toContain('id="tunerLink"');
    expect(playHtml).toContain('href="./tuner.html"');
    expect(playHtml).toContain('target="_blank"');
    expect(playHtml).toContain('rel="noopener"');
    expect(playHtml).toContain('body.play-view .tuning-panel');
    expect(playHtml).toContain('body.play-view .top-controls');
  });

  it("调牌器入口通过独立页面进入 tuner 视图", () => {
    const tunerHtml = readFileSync(path.join(prototypeRoot, "tuner.html"), "utf8");

    expect(tunerHtml).toContain("<title>胡了卜调牌器</title>");
    expect(tunerHtml).toContain('target.searchParams.set("view", "tuner")');
    expect(tunerHtml).toContain("./index.html");
  });

  it("脚本区分 play 和 tuner，并只在调牌器视图显示调参面板", () => {
    expect(playHtml).toContain('const PROTOTYPE_VIEW_MODES = new Set(["play", "tuner"]);');
    expect(playHtml).toContain('prototypeView: "play"');
    expect(playHtml).toContain('model.prototypeView === "tuner"');
    expect(playHtml).toContain("view.mountainTuningPanel.hidden = !shouldShowTuning");
  });

  it("密集牌山默认使用数百张小牌压力版参数", () => {
    expect(playHtml).toContain("const MOUNTAIN_DEFAULT_TILE_COUNT = 240;");
    expect(playHtml).toContain("const MOUNTAIN_TILE_COUNT_RANGE = { min: 120, max: 420 };");
    expect(playHtml).toContain("const MOUNTAIN_COORDINATE_SYSTEM = { baseWidth: 560, baseHeight: 640 };");
    expect(playHtml).toContain("const MOUNTAIN_RULE_TILE_SIZE = { width: 52, height: 70 };");
    expect(playHtml).toContain("const MOUNTAIN_INITIAL_AVAILABLE_TARGET = 8;");
    expect(playHtml).toContain("const MOUNTAIN_STACK_PREVIEW_DEPTH = 4;");
    expect(playHtml).toContain("const MOUNTAIN_MERGED_STACK_COUNT = 2;");
    expect(playHtml).toContain("const MOUNTAIN_ACTIVE_STACK_COUNT = 10;");
    expect(playHtml).toContain("const MOUNTAIN_STACK_OVERLAP_RANGE = { min: 0.05, max: 1 };");
    expect(playHtml).toContain("const BLOCKED_COVER_RATIO = 0.08;");
    expect(playHtml).toContain("const MOUNTAIN_PRIMARY_STACK_COUNT = 4;");
    expect(playHtml).toContain("const MOUNTAIN_PRIMARY_STACK_WEIGHT_MULTIPLIER = 2.45;");
    expect(playHtml).toContain("const MOUNTAIN_STACK_CLUSTER_PULL = 0.78;");
    expect(playHtml).toContain("const MOUNTAIN_TEMPLATE_IDS = [");
    expect(playHtml).toContain('"center-tower"');
    expect(playHtml).toContain('"two-wings"');
    expect(playHtml).toContain('"cross"');
    expect(playHtml).toContain('"ring"');
    expect(playHtml).toContain('"long-wall"');
    expect(playHtml).toContain('"islands"');
    expect(playHtml).toContain('"canyon"');
    expect(playHtml).toContain('"staircase"');
    expect(playHtml).toContain('"suspended-waist"');
    expect(playHtml).toContain('"suspended-waist": "悬台窄腰"');
    expect(playHtml).toContain("templateRegion");
    expect(playHtml).toContain("function getSuspendedWaistTemplateAnchors");
    expect(playHtml).toContain('"top-platform"');
    expect(playHtml).toContain('"waist"');
    expect(playHtml).toContain('"support-column"');
    expect(playHtml).toContain('"side-scatter"');
    expect(playHtml).toContain("const MOUNTAIN_AUTO_TEMPLATE_IDS = [");
    expect(playHtml).toContain("const MOUNTAIN_HIGH_PRESSURE_AUTO_TEMPLATE_IDS = [");
    expect(playHtml).toContain("function getAutoMountainTemplateIds()");
    expect(playHtml).toContain("function shouldUseHighPressureMountainAutoPool");
    expect(playHtml).toContain("function getMountainTemplateGenerationCandidates");
    expect(playHtml).toContain("function shouldRetryAutoMountainTemplate");
    expect(playHtml).toContain("function getGeneratedInitialAvailableCount");
    expect(playHtml).toContain('templateId: "auto"');
    expect(playHtml).toContain("tileCount: MOUNTAIN_DEFAULT_TILE_COUNT");
    expect(playHtml).toContain("stackDepth: 6");
    expect(playHtml).toContain("normalizeOptionalInteger(raw.tileCount, MOUNTAIN_TILE_COUNT_RANGE.min, MOUNTAIN_TILE_COUNT_RANGE.max)");
    expect(playHtml).toContain("normalizeMountainTemplateId(raw.templateId");
    expect(playHtml).toContain("function getFriendDemoGangTileKeys");
    expect(playHtml).toContain("orphanBudget");
    expect(playHtml).toContain("function assertFriendDemoOrphanRiskBudget");
    expect(playHtml).toContain("function getFriendDemoOrphanRiskSummary");
    expect(playHtml).toContain("function getFriendDemoOrphanRiskBudget");
    expect(playHtml).toContain("function buildRequiredTileIdentityQueue(tuning, reservedTileKeys = new Set())");
    expect(playHtml).toContain("function buildMountainFillerPatterns(level, random, tuning = null, reservedTileKeys = new Set())");
    expect(playHtml).toContain("function doesPatternUseReservedTile");
    expect(playHtml).toContain("function makeSuitCoveragePattern(suit, levelOrder, groupIndex)");
    expect(playHtml).toContain("function buildMixedWindowSolutionGroups");
    expect(playHtml).toContain("function canUseMixedWindowDistribution");
    expect(playHtml).toContain("mixedWindowRole");
    expect(playHtml).toContain("button.dataset.stackDepth");
    expect(playHtml).toContain("button.dataset.stackPreviewDepth");
    expect(playHtml).toContain("button.dataset.stackOverlapRatio");
    expect(playHtml).toContain("button.dataset.bridgeUnlocks");
    expect(playHtml).toContain("button.dataset.mixedWindowRole");
    expect(playHtml).toContain("content: attr(data-stack-depth);");
    expect(playHtml).not.toContain("content: attr(data-bridge-unlocks);");
    expect(playHtml).toContain('.tile[data-ui-skin="v6"].stack-bridge::after');
    expect(playHtml).toContain("content: none;");
    expect(playHtml).toContain("function createMountainBridgeGroups");
    expect(playHtml).toContain("function getMountainActiveTemplateAnchors");
    expect(playHtml).toContain("function refreshAutoMountainTemplateSeed");
    expect(playHtml).toContain("function getAutoMountainTemplateSeedText");
    expect(playHtml).toContain("function addMountainBridgePositions");
    expect(playHtml).toContain("function attachMountainBridgeBlockers");
    expect(playHtml).toContain("function createMountainStackOverlapProfile");
    expect(playHtml).toContain("function getStackVisiblePreviewDepth(tile)");
    expect(playHtml).toContain("function isVisibleStackDisplayTile(tile)");
    expect(playHtml).toContain("function getStackPreviewDepth(tile)");
    expect(playHtml).toContain("stack-preview");
    expect(playHtml).toContain("stack-bridge");
    expect(playHtml).toContain("return MOUNTAIN_RULE_TILE_SIZE;");
    expect(playHtml).toContain(".board[data-mode=\"mountain\"] .tile");
    expect(playHtml).toContain("body.play-view .app");
    expect(playHtml).toContain("grid-template-columns: minmax(0, 480px) 72px;");
    expect(playHtml).toContain("body.play-view .app {");
    expect(playHtml).toContain("grid-template-columns: minmax(0, 1fr) 56px;");
    expect(playHtml).toContain("align-items: start;");
    expect(playHtml).toContain("align-content: start;");
    expect(playHtml).toContain("max-height: calc(100vh - 24px);");
    expect(playHtml).toContain("body.play-view .board[data-mode=\"mountain\"]");
    expect(playHtml).toContain("grid-template-rows: auto auto auto auto auto;");
    expect(playHtml).toContain("width: min(100%, 330px);");
    expect(playHtml).toContain("width: 11.4285714286%;");
    expect(playHtml).toContain("aspect-ratio: 52 / 70;");
    expect(playHtml).toContain("aspect-ratio: 560 / 640;");
    expect(playHtml).toContain("min-height: 60px;");
    expect(playHtml).toContain("body.play-view .slot-cell");
    expect(playHtml).toContain("min-height: 44px;");
    expect(playHtml).toContain("justify-content: center;");
  });

  it("玩家页使用正式一屏 HUD，右侧只保留道具栏", () => {
    expect(playHtml).toContain('<section class="play-hud" aria-label="局内状态">');
    expect(playHtml).toContain('id="hudLevel"');
    expect(playHtml).toContain('id="hudGoal"');
    expect(playHtml).toContain('id="hudRemaining"');
    expect(playHtml).toContain('id="hudScore"');
    expect(playHtml).toContain('id="hudCoins"');
    expect(playHtml).toContain('<section class="section tools-section">');
    expect(playHtml).toContain("body.play-view .side > :not(.tools-section)");
    expect(playHtml).toContain("grid-template-columns: minmax(0, 480px) 72px;");
    expect(playHtml).toContain("body.play-view .tool-actions");
    expect(playHtml).toContain("grid-template-columns: minmax(0, 1fr) 56px;");
    expect(playHtml).toContain("grid-template-columns: repeat(var(--slot-count), minmax(26px, 1fr));");
    expect(playHtml).toContain('<div class="action-strip">');
    expect(playHtml).toContain("grid-template-columns: repeat(5, minmax(48px, 64px));");
    expect(playHtml).toContain("body.play-view .slot-area {");
    expect(playHtml).toContain("margin-bottom: 168px;");
    expect(playHtml).toContain("scroll-margin-bottom: 184px;");
    expect(playHtml).toContain("function renderPlayHud()");
    expect(playHtml).toContain("function getHudGoalText()");
    expect(playHtml).toContain("view.hudRemaining.textContent");
    expect(playHtml).toContain('restart.className = "primary-button";');
    expect(playHtml).toContain('restart.textContent = "重开";');
    expect(playHtml).not.toContain("牌山已清空，但 Boss 目标未完成：");
    expect(playHtml).not.toContain("当前卡在 ");
  });

  it("朋友试玩 Demo 编排为 20 关主线和右侧三道具", () => {
    expect(playHtml).toContain("const FRIEND_DEMO_LEVEL_COUNT = 20;");
    expect(playHtml).toContain("const ENDLESS_START_LAYER = 21;");
    expect(playHtml).toContain("const FRIEND_DEMO_TUTORIAL_SLOT_LIMIT = 6;");
    expect(playHtml).toContain("const FRIEND_DEMO_FULL_SLOT_LIMIT = 8;");
    expect(playHtml).toContain("const FRIEND_DEMO_BOSS_TRIAL_LEVEL_INDEX = 9;");
    expect(playHtml).toContain("const FRIEND_DEMO_FINAL_BOSS_LEVEL_INDEX = 19;");
    expect(playHtml).toContain("const FRIEND_DEMO_REWARD_LEVEL_INDEXES = [2, 5, 8, 12, 15, 18];");
    expect(playHtml).toContain("const FRIEND_DEMO_BOSS_TRIAL_REWARD_COINS = 180;");
    expect(playHtml).toContain('const FRIEND_DEMO_BOSS_TRIAL_TITLE = "终局试炼";');
    expect(playHtml).toContain('const FRIEND_DEMO_FINAL_BOSS_TITLE = "胡了卜王";');
    expect(playHtml).toContain('const FRIEND_DEMO_FIRST_REWARD_ID = "demo_slot_plus_2";');
    expect(playHtml).toContain("const FRIEND_DEMO_TUTORIAL_COMBOS = [\"peng\", \"chi\", \"gang\", \"hu\"];");
    expect(playHtml).toContain("const FRIEND_DEMO_DIFFICULTY_PROFILES = [");
    expect(playHtml).toContain('label: "正式入门"');
    expect(playHtml).toContain('label: "终章门前"');
    expect(playHtml).toContain('label: "胡了卜王"');
    expect(playHtml).toContain("tileCount: 72");
    expect(playHtml).toContain("tileCount: 328");
    expect(playHtml).toContain("tileCount: 334");
    expect(playHtml).toContain("tileCount: 340");
    expect(playHtml).toContain("honorWeight: 62");
    expect(playHtml).toContain("orphanBudget: 7");
    expect(playHtml).toContain("function createFriendDemoTutorialTiles");
    expect(playHtml).toContain("function getFriendDemoSlotLimit");
    expect(playHtml).toContain("function getFriendDemoLevelMode");
    expect(playHtml).toContain("function getFriendDemoDifficultyProfile");
    expect(playHtml).toContain("function getFriendDemoBossTrialGoals");
    expect(playHtml).toContain("function getFriendDemoFinalBossGoals");
    expect(playHtml).toContain("function isFriendDemoFinalBossLevel");
    expect(playHtml).toContain("function claimBossTrialReward");
    expect(playHtml).toContain("BOSS_TRIAL_PHASES");
    expect(playHtml).toContain("BOSS_TRIAL_VARIANTS");
    expect(playHtml).toContain("function getBossTrialDeck");
    expect(playHtml).toContain("function getBossReviewPayload");
    expect(playHtml).toContain("bossReview");
    expect(playHtml).toContain("阶段目标");
    expect(playHtml).toContain("2. 接线");
    expect(playHtml).toContain("阶段目标：先把本局流派主骨扣成一条线");
    expect(playHtml).not.toContain("阶段目标：先把当前路线主骨扣成一条线");
    expect(playHtml).toContain("4. 收官");
    expect(playHtml).toContain("Boss 奖励品质");
    expect(playHtml).toContain("高阶 Boss 变体");
    expect(playHtml).toContain("西风构筑：牌尾定口");
    expect(playHtml).toContain("西风构筑：照听锁线");
    expect(playHtml).toContain("ascension_rescue_backbag_plus_1");
    expect(playHtml).toContain("高阶构筑：翻袋续命");
    expect(playHtml).toContain("ascension_river_cutbank_plus_1");
    expect(playHtml).toContain("高阶构筑：截流压口");
    expect(playHtml).toContain("ascension_deadwall_blackout_plus_1");
    expect(playHtml).toContain("高阶构筑：关灯收刀");
    expect(playHtml).toContain("ascension_deadwall_lightsout_plus_1");
    expect(playHtml).toContain("高阶构筑：熄灯封卷");
    expect(playHtml).toContain("ascension_north_counterwall_plus_1");
    expect(playHtml).toContain("北风构筑：反推续墙");
    expect(playHtml).toContain("ascension_north_wallanchor_plus_1");
    expect(playHtml).toContain("北风构筑：定盘续命");
    expect(playHtml).toContain("function getBossReviewPayload(result) {");
    expect(playHtml).toContain("bossVariant: deck.variant.id,");
    expect(playHtml).toContain('"救场流": ["ascension_east_rescuekick_plus_1", "ascension_rescue_wall_plus_1", "ascension_east_cover_plus_1", "ascension_rescue_relay_plus_1", "ascension_rescue_backbag_plus_1"]');
    expect(playHtml).toContain('"顺手胡流·滚听": ["ascension_east_followseal_plus_1", "ascension_east_followlock_plus_1", "ascension_east_snaphu_plus_1", "ascension_east_rollstep_plus_1", "ascension_east_rollhu_plus_1"]');
    expect(playHtml).toContain('"顺手胡流·听成": ["ascension_east_snaphu_plus_1", "ascension_east_rollstep_plus_1", "ascension_east_rollhu_plus_1", "ascension_east_listenfinish_plus_1"]');
    expect(playHtml).toContain("ascension_east_listenfinish_plus_1");
    expect(playHtml).toContain('"收官流": ["ascension_tail_lantern_plus_1", "ascension_west_tailwindow_plus_1", "ascension_deadwall_settle_plus_1", "ascension_deadwall_latch_plus_1", "ascension_deadwall_blackout_plus_1", "ascension_deadwall_closebook_plus_1", "ascension_deadwall_blackseal_plus_1", "ascension_deadwall_lightsout_plus_1"]');
    expect(playHtml).toContain('"收官流·熄灯": ["ascension_deadwall_latch_plus_1", "ascension_deadwall_closebook_plus_1", "ascension_deadwall_blackout_plus_1", "ascension_deadwall_blackseal_plus_1", "ascension_deadwall_lightsout_plus_1"]');
    expect(playHtml).toContain('"收官流·灭灯": ["ascension_deadwall_closebook_plus_1", "ascension_deadwall_blackseal_plus_1", "ascension_deadwall_lightsout_plus_1", "ascension_deadwall_killlight_plus_1"]');
    expect(playHtml).toContain("ascension_deadwall_killlight_plus_1");
    expect(playHtml).toContain('"试炼流·封卷": ["ascension_west_triallock_plus_1", "ascension_west_trialverdict_plus_1", "ascension_west_trialgrade_plus_1", "ascension_west_trialstamp_plus_1", "ascension_west_trialseal_plus_1"]');
    expect(playHtml).toContain('"试炼流·交卷": ["ascension_west_trialgrade_plus_1", "ascension_west_trialstamp_plus_1", "ascension_west_trialseal_plus_1", "ascension_west_submitpaper_plus_1"]');
    expect(playHtml).toContain("ascension_west_submitpaper_plus_1");
    expect(playHtml).toContain('"护河续押·回账": ["ascension_south_rivercache_plus_1", "ascension_south_rivervault_plus_1", "ascension_south_riverdike_plus_1", "ascension_south_riveraudit_plus_1", "ascension_south_riverledger_plus_1"]');
    expect(playHtml).toContain('"护河续押·归账": ["ascension_south_riverdike_plus_1", "ascension_south_riveraudit_plus_1", "ascension_south_riverledger_plus_1", "ascension_south_settleledger_plus_1"]');
    expect(playHtml).toContain("ascension_south_settleledger_plus_1");
    expect(playHtml).toContain('"河控流": ["ascension_south_rivercontrol_plus_1", "ascension_river_tide_plus_1", "ascension_river_plus_1", "ascension_river_pacing_plus_1", "ascension_river_cutbank_plus_1"]');
    expect(playHtml).toContain('"稳压流": ["ascension_north_walllife_plus_1", "ascension_rescue_wall_plus_1", "ascension_north_bastion_plus_1", "ascension_north_tidehold_plus_1", "ascension_north_wallroute_plus_1", "ascension_north_wallfallback_plus_1", "ascension_north_counterwall_plus_1", "ascension_north_walllock_plus_1", "ascension_north_wallfinish_plus_1", "ascension_north_wallanchor_plus_1"]');
    expect(playHtml).toContain("ascension_north_foundation_plus_1");
    expect(playHtml).toContain('"稳压流·定盘": ["ascension_north_wallroute_plus_1", "ascension_north_wallfallback_plus_1", "ascension_north_counterwall_plus_1", "ascension_north_walllock_plus_1", "ascension_north_wallfinish_plus_1", "ascension_north_wallanchor_plus_1"]');
    expect(playHtml).toContain('"稳压流·压底": ["ascension_north_counterwall_plus_1", "ascension_north_walllock_plus_1", "ascension_north_wallfinish_plus_1", "ascension_north_wallanchor_plus_1", "ascension_north_foundation_plus_1"]');
    expect(playHtml).toContain("function getAscensionBuildVariantName(message = model.run.lastSpecialEventMessage)");
    expect(playHtml).toContain("basePool.push(...(ASCENSION_BUILD_REWARD_BONUSES[buildProfile.name] ?? []));");
    expect(playHtml).toContain("basePool.push(...(ASCENSION_BUILD_REWARD_BONUSES[buildVariantName] ?? []));");
    expect(playHtml).toContain('"西风试锋": ["西风构筑：试锋点火", "西风构筑：点火爆发", "西风构筑：照线织锋", "西风构筑：照线压口", "西风构筑：压注封口", "西风奖赏：西风照牌", "西风构筑：满听绝口"]');
    expect(playHtml).toContain('"西风定口": ["西风奖赏：照听追线", "西风构筑：牌尾定口", "西风构筑：照听锁线", "西风构筑：合刃封口", "西风构筑：听口合刃", "西风构筑：封喉定口"]');
    expect(playHtml).toContain('"西风收口": ["西风构筑：牌尾定线", "西风构筑：尾巡封口", "西风构筑：尾灯留门", "西风构筑：封灯收线", "西风构筑：牌尾定口"]');
    expect(playHtml).toContain('"北风封火": ["北风奖赏：封台堡垒", "北风构筑：封火抬潮", "北风构筑：收刀封火", "北风构筑：闷燃封火", "北风构筑：锁台收刀"]');
    expect(playHtml).toContain('"北风封尾": ["北风奖赏：牌尾封台", "北风构筑：压台封尾", "北风构筑：闭门收刀", "北风构筑：断门落锁", "北风构筑：尾门封死", "北风构筑：死锁封尾", "北风构筑：闷锁封尾", "北风构筑：尾门绝锁"]');
    expect(playHtml).toContain('"西风构筑：压注封口"');
    expect(playHtml).toContain('"西风构筑：合刃封口"');
    expect(playHtml).toContain('"北风构筑：断门落锁"');
    expect(playHtml).toContain('"东风构筑：试路织线"');
    expect(playHtml).toContain('"南风构筑：呼吸蓄押"');
    expect(playHtml).toContain('"西风构筑：押线读口"');
    expect(playHtml).toContain('"北风构筑：燃尽封口"');
    expect(playHtml).toContain("西风构筑：牌尾定口");
    expect(playHtml).toContain("西风构筑：照听锁线");
    expect(playHtml).toContain("西风构筑：牌尾定口");
    expect(playHtml).toContain("西风构筑：照听锁线");
    expect(playHtml).toContain("东风构筑：试路织线");
    expect(playHtml).toContain("东风能力：借势串拍");
    expect(playHtml).toContain("借势连碰");
    expect(playHtml).toContain("东风连手");
    expect(playHtml).toContain("碰流滚动");
    expect(playHtml).toContain("借势串拍");
    expect(playHtml).toContain("碰流滚动、借势连碰和第一波目标动作压到同一拍边上");
    expect(playHtml).toContain("补 1 次撤回，接借势连碰");
    expect(playHtml).toContain("留气护口");
    expect(playHtml).not.toContain("下轮护口建议：");
    expect(playHtml).not.toContain("下轮留气建议：");
    expect(playHtml).not.toContain("留气护口线和 Boss 中段收口目标错位");
    expect(playHtml).not.toContain("留气护口前的护符、备用位和中段缓冲都见底");
    expect(playHtml).not.toContain("下轮满注建议：");
    expect(playHtml).not.toContain("下轮刃听建议：");
    expect(playHtml).not.toContain("下轮压潮封台建议：");
    expect(playHtml).not.toContain("下轮死锁建议：");
    expect(playHtml).toContain("西风把试锋压注、押线读口和最后那口封口一起压到赔率线上了，后段更像先把窗口看清，再狠狠干一把吃满。");
    expect(playHtml).toContain("西风已经把照听收锋、牌尾定线和最后那口封口扣成一条定口线了。先补信息，或者顺着照听收锋把下一关压成更死的后段定口局。");
    expect(playHtml).toContain("北风已经把锁火封台、残局压尾和最后收官口锁成一口了。");
    expect(playHtml).toContain("终局死斗局");
    expect(playHtml).toContain("北风封尾已经不只是把残局拖住，而是开始把闭门、断门落锁和最后那一下封尾压成同一步。先补残局容错，或者把下一关直接压成断门封尾局。");
    expect(playHtml).toContain("西风定口·合刃专属奖励，把照听收锋、合刃封口和最后那口胡流一起咬成真正的听刃封胡线。");
    expect(playHtml).toContain("北风锁火·压潮专属奖励，把锁火封台、压潮收官和最后那一闷一起压成潮头闷杀的终局死斗线。");
    expect(playHtml).toContain("北风封尾·闷锁专属奖励，把闭门、断门落锁、死锁封尾和最后那下封尾一起闷成彻底不回头的终局尾门。");
    expect(playHtml).toContain("西风把试锋、看山和胡流赔率提前点热，后段不是单纯加分，而是要先读准窗口再把满注封胡吃干净。");
    expect(playHtml).toContain("北风把尾门已经关成死锁口了，终局更像先把退路封死，再把最后那下封尾狠狠干到底。");
    expect(playHtml).toContain("西风试锋·压注专属奖励，把试锋压注、胡流 +16、压注封口和最后那口胡流一起压成一把吃满赔率的封胡线。");
    expect(playHtml).toContain("西风定口·合刃专属奖励，把照听收锋、合刃封口和最后那口胡流一起咬成真正的听刃封胡线。");
    expect(playHtml).toContain("东风护路已经不只是顺手看线，而是开始把护路看山、最后回口和前段修正扣成同一条补口线。先补信息，或者把下一关直接压成回口护路局。");
    expect(playHtml).toContain("function getEffectiveMountainTuningForLevel");
    expect(playHtml).toContain("function getFriendDemoTutorialRequiredCombo");
    expect(playHtml).toContain("function hasCompletedFriendDemoTutorialCombo");
    expect(playHtml).toContain("function canClearCurrentLevel");
    expect(playHtml).toContain("function getFriendDemoRewardPool");
    expect(playHtml).toContain('runMode: "mainline"');
    expect(playHtml).toContain("function isEndlessMode()");
    expect(playHtml).toContain("function getEndlessLayerOrder");
    expect(playHtml).toContain("function getEndlessLevelIndex");
    expect(playHtml).toContain("function getEndlessDifficultyProfile");
    expect(playHtml).toContain("function getEndlessChapterProfile");
    expect(playHtml).toContain("function advanceAfterEndlessClear");
    expect(playHtml).toContain("章节 Boss");
    expect(playHtml).toContain("听牌封潮手");
    expect(playHtml).toContain("杠火压尾官");
    expect(playHtml).toContain("endlessLayer");
    expect(playHtml).toContain('requestedMode === "endless"');
    expect(playHtml).toContain("function getDailyMutatorProfile");
    expect(playHtml).toContain("今日词缀");
    expect(playHtml).toContain("今日奖励");
    expect(playHtml).toContain("dailyParticipationStreak");
    expect(playHtml).toContain("function getDailyParticipationStreak()");
    expect(playHtml).toContain("routeMasteryLevel");
    expect(playHtml).toContain("局外偏好第一档轻补一刀");
    expect(playHtml).toContain("局外偏好第二档轻补一刀");
    expect(playHtml).toContain("今日词缀：看山织线");
    expect(playHtml).toContain("今日词缀：余槽救场");
    expect(playHtml).toContain("今日词缀：挡墙续押");
    expect(playHtml).toContain("function createFriendDemoFixedReward");
    expect(playHtml).toContain("function useDiscardTool");
    expect(playHtml).toContain('id="discardButton"');
    expect(playHtml).toContain('id="discardCount"');
    expect(playHtml).toContain("<strong>洗牌</strong>");
    expect(playHtml).toContain("<strong>撤回</strong>");
    expect(playHtml).toContain("<strong>丢弃</strong>");
    expect(playHtml).toContain("view.discardButton");
    expect(playHtml).toContain("model.state.river");
    expect(playHtml).toContain("model.state.riverLimit");
  });

  it("支持高阶周目首版入口，并把周目参数透传到壳层", () => {
    expect(playHtml).toContain('requestedMode === "ascension"');
    expect(playHtml).toContain("ascensionLevel");
    expect(playHtml).toContain("ascensionName");
    expect(playHtml).toContain("ASCENSION_CONFIGS");
    expect(playHtml).toContain('"东风场"');
    expect(playHtml).toContain('"南风场"');
    expect(playHtml).toContain('"西风场"');
    expect(playHtml).toContain('"北风场"');
    expect(playHtml).toContain("高阶周目");
    expect(playHtml).toContain("equippedAscensionPerks");
    expect(playHtml).toContain("ascensionPerkSlots");
    expect(playHtml).toContain("getAscensionPerkPool");
    expect(playHtml).toContain("getAscensionRewardPool");
    expect(playHtml).toContain("高阶能力");
    expect(playHtml).toContain("高阶奖励");
    expect(playHtml).toContain("试锋");
    expect(playHtml).toContain("牌尾");
    expect(playHtml).toContain("封盘");
    expect(playHtml).toContain("迟火");
    expect(playHtml).toContain("河杠流");
    expect(playHtml).toContain("收官流");
    expect(playHtml).toContain("顺手胡流");
    expect(playHtml).toContain("救场流");
    expect(playHtml).toContain("function getAscensionSettlementHighlights");
    expect(playHtml).not.toContain("failureBottleneck");
    expect(playHtml).not.toContain("failureReviewLine");
    expect(playHtml).not.toContain("failureLine");
    expect(playHtml).not.toContain("failureBuildVsBossLine");
    expect(playHtml).not.toContain("failureCollapseLine");
    expect(playHtml).not.toContain("failureNextPriorityLine");
    expect(playHtml).not.toContain("recoveryOrder");
    expect(playHtml).not.toContain("tierFailureFocusLine");
    expect(playHtml).not.toContain("rewardDepth");
    expect(playHtml).not.toContain("tierTheme");
    expect(playHtml).not.toContain("tierThemeLine");
    expect(playHtml).not.toContain("ascensionReview");
    expect(playHtml).not.toContain("failureType");
    expect(playHtml).toContain("function getBossReviewPayload(result) {");
    expect(playHtml).toContain("起风试手");
    expect(playHtml).toContain("南桌偏门");
    expect(playHtml).toContain("西窗压注");
    expect(playHtml).toContain("北斗封台");
    expect(playHtml).toContain("东风试胆");
    expect(playHtml).toContain("南桌续押");
    expect(playHtml).toContain("西风照听");
    expect(playHtml).toContain("北风断尾");
    expect(playHtml).toContain("东风试路·压线");
    expect(playHtml).toContain("东风连手·串碰");
    expect(playHtml).toContain("南风挡墙·换气");
    expect(playHtml).toContain("顺手摸牌");
    expect(playHtml).toContain("稳压补墙");
    expect(playHtml).toContain("河杠涨潮");
    expect(playHtml).toContain("收官落灯");
    expect(playHtml).toContain("高阶构筑：顺路滚雪球");
    expect(playHtml).toContain("高阶构筑：目标彩排");
    expect(playHtml).toContain("高阶构筑：稳压补墙");
    expect(playHtml).toContain("高阶构筑：河杠涨潮");
    expect(playHtml).toContain("高阶构筑：顺路追胡");
    expect(playHtml).toContain("高阶构筑：尾灯留门");
    expect(playHtml).toContain("高阶构筑：灯下探牌");
    expect(playHtml).toContain("高阶构筑：护河续押");
    expect(playHtml).toContain("高阶构筑：迟尾缓燃");
    expect(playHtml).toContain("东风试路");
    expect(playHtml).toContain("东风护路");
    expect(playHtml).toContain("east-scout");
    expect(playHtml).toContain("east-guard");
    expect(playHtml).toContain("south-wall");
    expect(playHtml).toContain("west-close");
    expect(playHtml).toContain("north-tailhold");
    expect(playHtml).toContain("南风续墙");
    expect(playHtml).toContain("西风收口");
    expect(playHtml).toContain("北风封尾");
    expect(playHtml).toContain("东风构筑：串碰借势");
    expect(playHtml).toContain("东风构筑：护路看山");
    expect(playHtml).toContain("南风构筑：换气留墙");
    expect(playHtml).toContain("前段开线链");
    expect(playHtml).toContain("护河续押");
    expect(playHtml).toContain("试锋压注");
    expect(playHtml).toContain("终局死斗");
    expect(playHtml).toContain("后段照线收锋");
    expect(playHtml).toContain("终局锁火压尾");
    expect(playHtml).toContain("第二段要先把试锋、照线、读口和牌尾窗口校成同一条后段线。");
    expect(playHtml).toContain("接线段优先吃能把");
    expect(playHtml).toContain("别把收益拆到第二条线。");
    expect(playHtml).not.toContain("试锋、照线、牌尾定线和后段封口拆散了");
    expect(playHtml).not.toContain("下轮先把试锋、照线和胡流爆发压成同一条线");
    expect(playHtml).not.toContain("下轮先把牌尾缓冲留住，再把死斗收刀和最后封口压成同一条线");
    expect(playHtml).toContain("北风已经把锁火封台、残局压尾和最后收官口锁成一口了。先补护符，或者把下一关直接推成更紧的终局死斗局。");
    expect(playHtml).toContain("北风把牌尾缓冲和迟火拖到了后段，残局压尾也跟着锁住了。先补护符，或者把下一关压成慢热死斗局。");
    expect(playHtml).toContain("北风先把锁火封台扣死了，残局压尾和最后收官口只差再顶一拍。先补护符，或者把下一关压成锁台死斗局。");
    expect(playHtml).toContain("北风把残局压尾和压台封尾先顶住了，最后那口收刀就差一拍。先补缓冲，或者把下一关压成压台封尾局。");
    expect(playHtml).toContain("南风构筑：稳手续气");
    expect(playHtml).toContain("南风构筑：续墙补台");
    expect(playHtml).toContain("西风构筑：试锋点火");
    expect(playHtml).toContain("西风构筑：照听收锋");
    expect(playHtml).toContain("西风构筑：牌尾定线");
    expect(playHtml).toContain("西风构筑：尾巡封口");
    expect(playHtml).toContain("北风构筑：封火抬潮");
    expect(playHtml).toContain("北风构筑：锁火封台");
    expect(playHtml).toContain("北风构筑：封尾压台");
    expect(playHtml).toContain("北风构筑：残局压尾");
    expect(playHtml).toContain("西风试锋");
    expect(playHtml).toContain("西风收口");
    expect(playHtml).toContain("北风封火");
    expect(playHtml).toContain("北风封尾");
    expect(playHtml).toContain("东风能力：顺风起手");
    expect(playHtml).toContain("东风能力：探手看线");
    expect(playHtml).toContain("南风能力：封压续手");
    expect(playHtml).toContain("南风构筑：偏门护路");
    expect(playHtml).toContain("西风能力：照听抬潮");
    expect(playHtml).toContain("西风奖赏：照听定线");
    expect(playHtml).toContain("北风能力：压台风口");
    expect(playHtml).toContain("北风奖赏：封台堡垒");
    expect(playHtml).toContain("北风能力：锁火开台");
    expect(playHtml).toContain("北风能力：死斗封尾");
    expect(playHtml).toContain("东风连手");
    expect(playHtml).toContain("南风挡墙");
    expect(playHtml).toContain("补 1 次撤回，接借势连碰");
    expect(playHtml).toContain("下一关碰流 +14 分，接借势串拍");
    expect(playHtml).toContain("备用位 +1，接封线留气");
    expect(playHtml).toContain("下一关胡流 +12 分，接封线留气");
    expect(playHtml).toContain("补 1 次丢弃，接最后封口");
    expect(playHtml).toContain("下一关胡流 +18 分，接迟火收刀");
    expect(playHtml).toContain("补 1 次丢弃，接最后收官口");
    expect(playHtml).toContain("西风照牌");
    expect(playHtml).toContain("北风固台");
    expect(playHtml).toContain("东风奖赏：起手顺风");
    expect(playHtml).toContain("东风奖赏：东风连手");
    expect(playHtml).toContain("东风构筑：东风连手");
    expect(playHtml).toContain("东风构筑：连手接路");
    expect(playHtml).toContain("东风构筑：借势连碰");
    expect(playHtml).toContain("东风构筑：探手接线");
    expect(playHtml).toContain("东风构筑：稳手连牌");
    expect(playHtml).toContain("前段压线");
    expect(playHtml).toContain("串碰接路");
    expect(playHtml).toContain("南风构筑：续墙稳台");
    expect(playHtml).toContain("南风构筑：护口封线");
    expect(playHtml).toContain("南风构筑：续墙收口");
    expect(playHtml).toContain("南风构筑：南风挡墙");
    expect(playHtml).toContain("缓收稳口");
    expect(playHtml).toContain("顶墙换气");
    expect(playHtml).toContain("高阶奖励：胡流 +8");
    expect(playHtml).toContain("高阶奖励：杠流 +8");
    expect(playHtml).toContain('"西风试锋": ["ascension_hu_score_plus_1", "ascension_west_tracefire_plus_1", "ascension_west_signal_plus_1", "ascension_west_accountbook_plus_1", "ascension_west_focus_plus_1", "ascension_west_variant_plus_1", "ascension_west_flareburst_plus_1", "ascension_west_signalweave_plus_1", "ascension_west_lineburn_plus_1", "ascension_west_wagerseal_plus_1", "ascension_west_wagerline_plus_1", "ascension_west_wagerallin_plus_1", "ascension_west_cashout_plus_1"]');
    expect(playHtml).toContain('"seal-table+late-flare": ["ascension_north_flarehold_plus_1", "ascension_north_lockfire_plus_1", "ascension_north_finishfire_plus_1", "ascension_north_lockhold_plus_1", "ascension_north_lockblade_plus_1", "ascension_north_tailvault_plus_1"]');
    expect(playHtml).toContain('"north-lockhold+north-tailhold": ["ascension_north_lockhold_plus_1", "ascension_north_tailhold_plus_1", "ascension_north_tailpress_plus_1", "ascension_north_endseal_plus_1", "ascension_north_tidehold_plus_1"]');
    expect(playHtml).toContain('\"东风试路\": [\"东风试路\", \"东风试路·压线\", \"东风试路·起风\", \"东风试路·定风\", \"东风试胆\", \"东风织口\"]');
    expect(playHtml).toContain('\"东风探手\": [\"东风探手\", \"东风探手·压口\"]');
    expect(playHtml).toContain('\"东风护路\": [\"东风护路\", \"东风护路·收束\", \"东风护路·回口\"]');
    expect(playHtml).toContain('\"东风连手\": [\"东风连手\", \"东风连手·串碰\", \"东风连手·借势\", \"东风连手·串拍\", \"东风借碰\"]');
    expect(playHtml).toContain('\"南风护口\": [\"南风护口\", \"南风护口·缓封\", \"南风护口·留气\"]');
    expect(playHtml).toContain('\"南风稳手\": [\"南风稳手\", \"南风稳手·缓收\", \"南桌偏门\"]');
    expect(playHtml).toContain('\"南风续墙\": [\"南风续墙\", \"南风续墙·封台\", \"南风续墙·蓄口\", \"南桌续押\", \"南墙收口\"]');
    expect(playHtml).toContain('\"南风挡墙\": [\"南风挡墙\", \"南风挡墙·换气\", \"南风挡墙·墙脉\", \"南风挡墙·回潮\", \"南风留墙\"]');
    expect(playHtml).toContain('\"西风试锋\": [\"西风试锋\", \"西风试锋·点火\", \"西风试锋·照线\", \"西风试锋·压注\", \"西风试锋·赔率\", \"西风试锋·收注\", \"西窗压注\", \"西窗满注\"]');
    expect(playHtml).toContain('\"西风收口\": [\"西风收口\", \"西风收口·留门\", \"西风收口·封灯\", \"西风收口·锁门\"]');
    expect(playHtml).toContain('\"西风定口\": [\"西风定口\", \"西风定口·牌尾\", \"西风定口·照听\", \"西风定口·合刃\", \"西风定口·封喉\", \"西风定口·听刃\", \"西风照听\", \"西风刃听\"]');
    expect(playHtml).toContain('\"北风封火\": [\"北风封火\", \"北风封火·收刀\", \"北风封火·闷燃\", \"北斗封台\"]');
    expect(playHtml).toContain('\"北风锁火\": [\"北风锁火\", \"北风锁火·锁台\", \"北风锁火·迟尾\", \"北风锁火·压潮\", \"北风锁火·终煤\", \"北风锁火·熄潮\", \"北风锁火·封潮\", \"北斗压潮\"]');
    expect(playHtml).toContain('\"北风封尾\": [\"北风封尾\", \"北风封尾·压台\", \"北风封尾·闭门\", \"北风封尾·断门\", \"北风封尾·闷锁\", \"北风封尾·绝锁\", \"北风断尾\", \"北风死锁\"]');
    expect(playHtml).toContain("试锋压注");
    expect(playHtml).toContain("定口合刃");
    expect(playHtml).toContain("西风构筑：照线压口");
    expect(playHtml).toContain("北风构筑：锁台死斗");
    expect(playHtml).toContain("北风构筑：锁台收刀");
    expect(playHtml).toContain("北风构筑：迟尾死斗");
    expect(playHtml).toContain("北风构筑：压台封尾");
    expect(playHtml).toContain("北风构筑：闭门收刀");
    expect(playHtml).toContain("锁火压潮");
    expect(playHtml).toContain("断门封尾");
    expect(playHtml).toContain("西风奖赏：照听追线");
    expect(playHtml).toContain("北风奖赏：封台堡垒");
    expect(playHtml).toContain("北风已经把锁火封台、残局压尾和最后收官口锁成一口了。先补护符，或者把下一关直接推成更紧的终局死斗局。");
    expect(playHtml).toContain("北风把残局压尾和压台封尾先顶住了，最后那口收刀就差一拍。先补缓冲，或者把下一关压成压台封尾局。");
    expect(playHtml).toContain('"deadwall-cache+late-flare": ["ascension_late_deadwall_mix_plus_1", "ascension_north_lockdown_plus_1", "ascension_north_slowburn_plus_1"]');
    expect(playHtml).toContain('"deadwall-cache+seal-table": ["ascension_sealed_deadwall_mix_plus_1", "ascension_north_bastion_plus_1", "ascension_north_closedoor_plus_1"]');
    expect(playHtml).toContain("北风先把锁火封台扣死了，残局压尾和最后收官口只差再顶一拍。先补护符，或者把下一关压成锁台死斗局。");
    expect(playHtml).toContain("北风把残局压尾和压台封尾先顶住了，最后那口收刀就差一拍。先补缓冲，或者把下一关压成压台封尾局。");
    expect(playHtml).toContain("西风已经把牌尾定线、尾巡封口和尾灯留门拧成一条收线链了。你可以先补一口收线资源，或者顺着杠流 +8 和尾灯留门把下一关压成更死的牌尾收口局。");
    expect(playHtml).toContain("回生接力");
    expect(playHtml).toContain("试口落灯");
    expect(playHtml).toContain("稳河回手");
    expect(playHtml).toContain("震山发力");
    expect(playHtml).toContain("顺手封拍");
    expect(playHtml).toContain("顶库续押");
    expect(playHtml).toContain("对卷落口");
    expect(playHtml).toContain("回墙续命");
    expect(playHtml).toContain("高阶构筑：回生接力");
    expect(playHtml).toContain("高阶构筑：收官试口");
    expect(playHtml).toContain("高阶构筑：稳河回拍");
    expect(playHtml).toContain("高阶构筑：震山爆线");
    expect(playHtml).toContain("高阶构筑：顺手扣拍");
    expect(playHtml).toContain("南风构筑：顶库续押");
    expect(playHtml).toContain("西风构筑：对卷落口");
    expect(playHtml).toContain("北风构筑：回墙续命");
    expect(playHtml).toContain("ascension_east_borrowwind_plus_1");
    expect(playHtml).toContain("ascension_south_bulwark_plus_1");
    expect(playHtml).toContain("ascension_west_readbook_plus_1");
    expect(playHtml).toContain("ascension_north_lockfire_plus_1");
    expect(playHtml).toContain("ascension_north_finishfire_plus_1");
    expect(playHtml).not.toContain("高阶专属封面·构筑回顾：");
    expect(playHtml).not.toContain("高阶专属封面·本轮关键得失：");
    expect(playHtml).not.toContain("高阶专属封面·下一轮第一手：");
    expect(playHtml).not.toContain("高阶成功封面·构筑回顾：");
    expect(playHtml).not.toContain("高阶成功封面·本轮关键收益：");
    expect(playHtml).not.toContain("高阶成功封面·本轮高阶身份：");
    expect(playHtml).not.toContain("高阶成功封面·下一轮第一手：");
    expect(playHtml).toContain("东风探手·压口");
    expect(playHtml).not.toContain("nextDecision");
    expect(playHtml).not.toContain("tempoRead");
    expect(playHtml).not.toContain("rewardChainVerdict");
    expect(playHtml).not.toContain("路线决策：");
    expect(playHtml).not.toContain("节奏读法：");
    expect(playHtml).not.toContain("奖励链判定：");
    expect(playHtml).not.toContain("eventIdentityVerdict");
    expect(playHtml).not.toContain("事件身份判定：");
    expect(playHtml).not.toContain("buildIdentityVerdict");
    expect(playHtml).not.toContain("构筑手感判定：");
    expect(playHtml).not.toContain("bossPressureVerdict");
    expect(playHtml).not.toContain("Boss 压力判定：");
    expect(playHtml).toContain("ascension_east_openerhythm_plus_1");
    expect(playHtml).toContain("东风构筑：三拍开线");
    expect(playHtml).toContain("ascension_south_breathwall_core_plus_1");
    expect(playHtml).toContain("南风构筑：呼吸墙核");
    expect(playHtml).toContain("ascension_west_accountbook_plus_1");
    expect(playHtml).toContain("西风构筑：读账封口");
    expect(playHtml).toContain("ascension_north_finalblade_plus_1");
    expect(playHtml).toContain("北风构筑：终局封刀");
    expect(playHtml).toContain("东风能力：起风探手");
    expect(playHtml).toContain("东风构筑：连手起势");
    expect(playHtml).toContain("东风试路·起风");
    expect(playHtml).toContain("起风探手");
    expect(playHtml).toContain("东风试路·定风");
    expect(playHtml).toContain("东风构筑：定风开线");
    expect(playHtml).not.toContain("下轮起风建议：");
    expect(playHtml).toContain("南风能力：缓口留气");
    expect(playHtml).toContain("南风构筑：墙脉续押");
    expect(playHtml).toContain("南风挡墙·墙脉");
    expect(playHtml).toContain("墙脉续押");
    expect(playHtml).toContain("南风挡墙·回潮");
    expect(playHtml).toContain("南风构筑：回潮反推");
    expect(playHtml).not.toContain("下轮墙脉建议：");
    expect(playHtml).toContain("西风能力：赔率点火");
    expect(playHtml).toContain("西风构筑：双刃并口");
    expect(playHtml).toContain("西风试锋·赔率");
    expect(playHtml).toContain("赔率点火");
    expect(playHtml).toContain("西风试锋·收注");
    expect(playHtml).toContain("西风构筑：收注封账");
    expect(playHtml).toContain("西风把赔率点火后的窗口收到账面上，后段不是继续加注，而是把看山读口、满注封胡和最后封口压成真正收账。");
    expect(playHtml).not.toContain("下轮收注建议：");
    expect(playHtml).not.toContain("这轮先回看的是收注封账");
    expect(playHtml).not.toContain("这轮真正散掉的是收注封账后的最后封口");
    expect(playHtml).not.toContain("下一轮第一手先把西风构筑：收注封账");
    expect(playHtml).not.toContain("下轮赔率建议：");
    expect(playHtml).toContain("北风能力：终煤压潮");
    expect(playHtml).toContain("北风构筑：断门横闩");
    expect(playHtml).toContain("北风锁火·终煤");
    expect(playHtml).toContain("终煤压潮");
    expect(playHtml).toContain("北风锁火·熄潮");
    expect(playHtml).toContain("北风构筑：熄潮封局");
    expect(playHtml).toContain("北风锁火·熄潮");
    expect(playHtml).toContain("熄潮封局");
    expect(playHtml).toContain("终煤压潮");
    expect(playHtml).not.toContain("下轮熄潮建议：");
    expect(playHtml).not.toContain("这轮先回看的是熄潮封局");
    expect(playHtml).not.toContain("这轮真正散掉的是熄潮封局前的最后收官");
    expect(playHtml).not.toContain("下一轮第一手先把北风构筑：熄潮封局");
    expect(playHtml).not.toContain("下轮终煤建议：");
    expect(playHtml).toContain("南风续墙·蓄口");
    expect(playHtml).toContain("续墙稳台");
    expect(playHtml).toContain("西风定口·封喉");
    expect(playHtml).toContain("照听收锋");
    expect(playHtml).toContain("刃口收死");
    expect(playHtml).toContain("北风封尾·闷锁");
    expect(playHtml).toContain("死锁封尾");
    expect(playHtml).toContain("东风连手已经把碰流滚动、借势连碰和第一波目标动作压到同一拍边上了。");
    expect(playHtml).toContain("补 1 次撤回，接借势连碰");
    expect(playHtml).toContain("下一关碰流 +20 分，接串拍压直");
    expect(playHtml).toContain("南风挡墙已经把护符墙、中段换气和挡墙收口滚到同一拍了");
    expect(playHtml).toContain("补 1 次护符，接护符墙");
    expect(playHtml).toContain("下一关高压，通关 +222 铜钱，接挡墙收口");
    expect(playHtml).toContain("西风把试锋压注、押线读口和最后那口封口一起压到赔率线上了");
    expect(playHtml).toContain("下一关胡流 +18 分，接赔率封口");
    expect(playHtml).toContain("下一关禁透视，通关 +224 铜钱，接吃满赔率");
    expect(playHtml).toContain("北风把锁火封台、压潮窗口和最后那一闷一起顶到潮头上了");
    expect(playHtml).toContain("补 1 次护符，接潮头封台");
    expect(playHtml).toContain("下一关杠流 +22 分，接潮尾闷口");
    expect(playHtml).toContain('"西风试锋": ["西风构筑：试锋点火", "西风构筑：点火爆发", "西风构筑：照线织锋", "西风构筑：照线压口", "西风构筑：压注封口", "西风奖赏：西风照牌", "西风构筑：满听绝口"]');
    expect(playHtml).toContain('"北风锁火": ["北风构筑：锁火封台", "北风能力：锁火开台", "北风构筑：残局压尾", "北风构筑：压潮收官", "北风构筑：潮头闷杀", "北风构筑：潮尾封闷", "北风构筑：熄潮封局"]');
    expect(playHtml).toContain("西风把试锋压注、押线读口和最后那口封口一起压到赔率线上了，后段更像先把窗口看清，再狠狠干一把吃满。");
    expect(playHtml).toContain("西风把试锋和胡流烧成同一口了，后段先点火再收锋会更稳。");
    expect(playHtml).toContain("西风把照线和收锋先拧成一条了，后段更像看清目标后再压爆发。");
    expect(playHtml).toContain("北风已经把封盘护符、迟火翻局和封台收刀点成终局火力了。你可以先稳住护符，或者顺着胡流 +8、迟火翻局和封台收刀把下一关压成更狠的迟火收刀局。");
    expect(playHtml).toContain("顺着胡流 +8 把下一关直接压成胡流点火局");
    expect(playHtml).toContain("下一关杠流 +14 分，接尾灯留门");
    expect(playHtml).toContain("尾灯留门");
    expect(playHtml).toContain("下一关杠流 +18 分，接留门收线");
    expect(playHtml).toContain("顺着胡流 +8、迟火翻局和封台收刀把下一关压成更狠的迟火收刀局");
    expect(playHtml).toContain("收刀封火");
    expect(playHtml).toContain("下一关胡流 +20 分，接收刀封火");
    expect(playHtml).toContain("下一关杠流 +18 分，接残局收刀");
    expect(playHtml).toContain("西风构筑：压注封口");
    expect(playHtml).toContain("西风构筑：满注封胡");
    expect(playHtml).toContain("西风构筑：合刃封口");
    expect(playHtml).toContain("西风构筑：刃口收死");
    expect(playHtml).toContain("北风构筑：压潮收官");
    expect(playHtml).toContain("北风构筑：潮头闷杀");
    expect(playHtml).toContain("北风构筑：断门落锁");
    expect(playHtml).toContain("北风构筑：死锁封尾");
    expect(playHtml).toContain("下一关胡流 +18 分，接赔率封口");
    expect(playHtml).toContain("补 1 次看山，接押线读口");
    expect(playHtml).toContain("补 1 次丢弃，接合刃封口");
    expect(playHtml).toContain("补 1 次看山，接听口合刃");
    expect(playHtml).toContain("下一关杠流 +22 分，接潮尾闷口");
    expect(playHtml).toContain("补 1 次护符，接潮头封台");
    expect(playHtml).toContain("补 1 次护符，接断门落锁");
    expect(playHtml).toContain("备用位 +1，接尾门封死");
    expect(playHtml).toContain("西窗满注");
    expect(playHtml).toContain("西风刃听");
    expect(playHtml).toContain("北斗压潮");
    expect(playHtml).toContain("北风死锁");
    expect(playHtml).toContain("东风织口");
    expect(playHtml).toContain("东风借碰");
    expect(playHtml).toContain("南墙收口");
    expect(playHtml).toContain("东风场先稳手再顺路，偏前段开线、探手中继和第一波目标节奏。");
    expect(playHtml).toContain("南风场更偏中段稳压、偏门换气和会呼吸的续墙防线。");
    expect(playHtml).toContain("西风场更偏后段试锋、照听锁线和牌尾定口成型。");
    expect(playHtml).toContain("北风场更偏封火烧透、压潮闷杀和终局收刀死斗。");
    expect(playHtml).toContain('return { name: "东风试路", detail: "偏撤回修正、看山预判和起手试路。" };');
    expect(playHtml).toContain('return { name: "南风续墙", detail: "偏护符、备用位和中段续墙。" };');
    expect(playHtml).toContain('return { name: "西风试锋", detail: "偏试锋点火、照线和后段胡流爆发。" };');
    expect(playHtml).toContain('return { name: "北风封火", detail: "偏封盘护符、迟火爆发和终局收刀。" };');
    expect(playHtml).toContain("南风留墙");
    expect(playHtml).toContain("补 1 次看山，接满注封胡");
    expect(playHtml).toContain("下一关胡流 +20 分，接满注封胡");
    expect(playHtml).toContain("补 1 次看山，接刃口收死");
    expect(playHtml).toContain("下一关杠流 +24 分，接潮头闷杀");
    expect(playHtml).toContain("备用位 +1，接死锁封尾");
    expect(playHtml).toContain("补 1 次看山，接压线织口");
    expect(playHtml).toContain("下一关碰流 +14 分，接织口压线");
    expect(playHtml).toContain("补 1 次撤回，接借势连碰");
    expect(playHtml).toContain("下一关碰流 +18 分，接借碰滚线");
    expect(playHtml).toContain("补 1 次护符，接续墙收口");
    expect(playHtml).toContain("下一关禁洗牌，通关 +216 铜钱，接收口封台");
    expect(playHtml).toContain("补 1 次护符，接换气留墙");
    expect(playHtml).toContain("备用位 +1，接留墙稳压");
    expect(playHtml).toContain('"西风试锋": ["西风试锋", "西风试锋·点火", "西风试锋·照线", "西风试锋·压注", "西风试锋·赔率", "西风试锋·收注", "西窗压注", "西窗满注"]');
    expect(playHtml).toContain('"西风定口": ["西风定口", "西风定口·牌尾", "西风定口·照听", "西风定口·合刃", "西风定口·封喉", "西风定口·听刃", "西风照听", "西风刃听"]');
    expect(playHtml).toContain('"北风锁火": ["北风锁火", "北风锁火·锁台", "北风锁火·迟尾", "北风锁火·压潮", "北风锁火·终煤", "北风锁火·熄潮", "北风锁火·封潮", "北斗压潮"]');
    expect(playHtml).toContain('"北风封尾": ["北风封尾", "北风封尾·压台", "北风封尾·闭门", "北风封尾·断门", "北风封尾·闷锁", "北风封尾·绝锁", "北风断尾", "北风死锁"]');
    expect(playHtml).toContain('"东风试路": ["东风试路", "东风试路·压线", "东风试路·起风", "东风试路·定风", "东风试胆", "东风织口"]');
    expect(playHtml).toContain('"东风连手": ["东风连手", "东风连手·串碰", "东风连手·借势", "东风连手·串拍", "东风借碰"]');
    expect(playHtml).toContain('"南风护口": ["南风护口", "南风护口·缓封", "南风护口·留气"]');
    expect(playHtml).toContain("东风构筑：借势双拍");
    expect(playHtml).toContain("南风构筑：留气护口");
    expect(playHtml).toContain('"ascension_east_doubleborrow_plus_1"');
    expect(playHtml).toContain('"ascension_south_holdbank_plus_1"');
    expect(playHtml).toContain('"东风护路": ["东风护路", "东风护路·收束", "东风护路·回口"]');
    expect(playHtml).toContain('"南风续墙": ["南风续墙", "南风续墙·封台", "南风续墙·蓄口", "南桌续押", "南墙收口"]');
    expect(playHtml).toContain('"南风挡墙": ["南风挡墙", "南风挡墙·换气", "南风挡墙·墙脉", "南风挡墙·回潮", "南风留墙"]');
    expect(playHtml).toContain('"西风试锋": ["ascension_hu_score_plus_1", "ascension_west_tracefire_plus_1", "ascension_west_signal_plus_1", "ascension_west_accountbook_plus_1", "ascension_west_focus_plus_1", "ascension_west_variant_plus_1", "ascension_west_flareburst_plus_1", "ascension_west_signalweave_plus_1", "ascension_west_lineburn_plus_1", "ascension_west_wagerseal_plus_1", "ascension_west_wagerline_plus_1", "ascension_west_wagerallin_plus_1", "ascension_west_cashout_plus_1"]');
    expect(playHtml).toContain('"西风定口": ["ascension_hu_score_plus_1", "ascension_west_focus_plus_1", "ascension_west_judgeline_plus_1", "ascension_west_accountbook_plus_1", "ascension_west_bladeecho_plus_1", "ascension_west_tailmark_plus_1", "ascension_west_close_plus_1", "ascension_west_tailpress_plus_1", "ascension_west_listenpress_plus_1", "ascension_west_tailblade_plus_1", "ascension_west_listenlock_plus_1", "ascension_west_listenblade_plus_1", "ascension_west_bindcut_plus_1", "ascension_west_bindlisten_plus_1", "ascension_west_bindkill_plus_1", "ascension_west_throatseal_plus_1", "ascension_west_listenkill_plus_1"]');
    expect(playHtml).toContain('"北风锁火": ["ascension_hu_score_plus_1", "ascension_north_lockhold_plus_1", "ascension_north_lockfire_plus_1", "ascension_north_surgeguard_plus_1", "ascension_north_coalwall_plus_1", "ascension_north_finalblade_plus_1", "ascension_north_deadwall_plus_1", "ascension_north_locktower_plus_1", "ascension_north_slowburn_plus_1", "ascension_north_surgepress_plus_1", "ascension_north_surgekill_plus_1", "ascension_north_endseal_plus_1", "ascension_north_extinguish_plus_1", "ascension_north_tideseal_plus_1"]');
    expect(playHtml).toContain('"北风封尾": ["ascension_gang_score_plus_1", "ascension_north_tailhold_plus_1", "ascension_north_finalblade_plus_1", "ascension_north_deadwall_plus_1", "ascension_north_laststand_plus_1", "ascension_north_tailpress_plus_1", "ascension_north_closedoor_plus_1", "ascension_north_breakseal_plus_1", "ascension_north_tailgate_plus_1", "ascension_north_deadlock_plus_1", "ascension_north_smotherlock_plus_1", "ascension_north_totallock_plus_1"]');
    expect(playHtml).toContain("西风试锋·压注专属奖励，把试锋压注、胡流 +16、压注封口和最后那口胡流一起压成一把吃满赔率的封胡线。");
    expect(playHtml).toContain("西风定口·合刃专属奖励，把照听收锋、合刃封口、最后定口和收死那一下更狠地咬成一刀终局。");
    expect(playHtml).toContain("北风锁火·压潮专属奖励，把锁火封台、压潮收官和最后那一闷一起压成潮头闷杀的终局死斗线。");
    expect(playHtml).toContain("北风封尾·断门专属奖励，把闭门、断门落锁、尾门封死和最后封尾一起压成不再回头的死锁终局。");
    expect(playHtml).toContain("西风定口·合刃专属奖励");
    expect(playHtml).toContain("北风锁火·压潮专属奖励，把锁火封台、压潮收官和最后那一闷一起压成潮头闷杀的终局死斗线。");
    expect(playHtml).toContain("北风把封盘护符和牌尾整理先关住了门，残局收刀也更容易留到最后一口。先补容错，或者把下一关压成闭门封尾局。");
    expect(playHtml).not.toContain("下轮压注建议：");
    expect(playHtml).not.toContain("下轮合刃建议：");
    expect(playHtml).not.toContain("下轮压潮建议：");
    expect(playHtml).not.toContain("下轮断门建议：");
    expect(playHtml).toContain("西风把试锋线摆到桌面上了。你可以先看山试锋，也可以顺着胡流 +8 把下一关直接压成胡流点火局。");
    expect(playHtml).toContain("西风已经把牌尾定线、尾巡封口和尾灯留门拧成一条收线链了。你可以先补一口收线资源，或者顺着杠流 +8 和尾灯留门把下一关压成更死的牌尾收口局。");
    expect(playHtml).toContain("北风已经把封盘护符、迟火翻局和封台收刀点成终局火力了。你可以先稳住护符，或者顺着胡流 +8、迟火翻局和封台收刀把下一关压成更狠的迟火收刀局。");
    expect(playHtml).toContain("北风把牌尾、残局封口和最后那下封尾都锁上了。你可以先补缓冲，或者顺着杠流 +8 把下一关压成真正的封尾死斗局。");
    expect(playHtml).toContain('"东风试路": ["东风构筑：稳手连牌", "东风构筑：起手试路", "东风构筑：顺路起手", "东风构筑：前段压线"]');
    expect(playHtml).toContain('"东风试路": ["ascension_east_trace_plus_1", "ascension_east_scout_plus_1", "ascension_east_readmouth_plus_1", "ascension_east_openerhythm_plus_1", "ascension_east_trailhead_plus_1", "ascension_east_pressureline_plus_1", "ascension_east_pressureseal_plus_1", "ascension_east_pressureweave_plus_1", "ascension_east_routeguard_plus_1", "ascension_east_route_plus_1", "ascension_east_routeweave_plus_1", "ascension_east_setwind_plus_1"]');
    expect(playHtml).toContain('"东风探手": ["东风构筑：探手接线", "东风构筑：探手试线", "东风构筑：试线压口"]');
    expect(playHtml).toContain("东风构筑：护路收束");
    expect(playHtml).toContain("东风护路·回口");
    expect(playHtml).toContain("东风构筑：护路回口");
    expect(playHtml).toContain("东风构筑：压线织口");
    expect(playHtml).toContain("东风构筑：试路护口");
    expect(playHtml).toContain("南风构筑：续墙封台");
    expect(playHtml).toContain("南风续墙·蓄口");
    expect(playHtml).toContain("南风构筑：续墙蓄口");
    expect(playHtml).toContain("东风护路已经不只是顺手看线，而是开始把护路看山、最后回口和前段修正扣成同一条补口线。先补信息，或者把下一关直接压成回口护路局。");
    expect(playHtml).toContain("补 1 次看山，接护路回口");
    expect(playHtml).toContain("东风护路·回口专属奖励，把护路看山、护路收束和最后那口回线继续扣成更完整的前段护口线。");
    expect(playHtml).toContain("南风续墙已经把续墙稳台、换气窗口和最后那口蓄压扣成一条了。先补墙脚，或者顺着蓄口线把下一关拖成更厚的后段收束局。");
    expect(playHtml).toContain("补 1 次护符，接续墙蓄口");
    expect(playHtml).toContain("南风续墙·蓄口专属奖励，把续墙稳台、后段换气和最后那口蓄压继续拖成会呼吸的后段收束线。");
    expect(playHtml).toContain('"东风护路": ["ascension_east_cover_plus_1", "ascension_east_cover_hold_plus_1", "ascension_east_route_plus_1", "ascension_wind_open_plus_1", "ascension_east_pressureseal_plus_1", "ascension_east_guardlane_plus_1", "ascension_east_guardmouth_plus_1"]');
    expect(playHtml).toContain('"南风续墙": ["ascension_south_wall_plus_1", "ascension_south_wallshield_plus_1", "ascension_south_breathwall_core_plus_1", "ascension_south_bulwark_plus_1", "ascension_south_wallseal_plus_1", "ascension_rescue_wall_plus_1", "ascension_south_wallroute_plus_1", "ascension_south_wallbreathe_plus_1", "ascension_south_wallbank_plus_1"]');
    expect(playHtml).toContain('"ascension_east_guardmouth_plus_1"');
    expect(playHtml).toContain('"ascension_south_wallbank_plus_1"');
    expect(playHtml).toContain('"南风稳手": ["ascension_south_steady_plus_1", "ascension_south_bank_plus_1", "ascension_south_breathhold_plus_1", "ascension_south_softseal_plus_1", "ascension_south_softbreath_plus_1", "ascension_south_softbank_plus_1", "ascension_south_wall_plus_1", "ascension_south_breathbank_plus_1"]');
    expect(playHtml).toContain('"东风连手": ["ascension_east_chain_build_plus_1", "ascension_east_chain_link_plus_1", "ascension_east_openerhythm_plus_1", "ascension_east_chainborrow_plus_1", "ascension_east_scout_plus_1", "ascension_east_momentum_plus_1", "ascension_east_borrowwind_plus_1", "ascension_east_penglane_plus_1", "ascension_east_doubleborrow_plus_1"]');
    expect(playHtml).toContain('"南风护口": ["ascension_south_hold_plus_1", "ascension_south_steady_plus_1", "ascension_south_wall_plus_1", "ascension_south_holdbreathe_plus_1", "ascension_south_softlock_plus_1", "ascension_south_safeseal_plus_1", "ascension_south_holdbank_plus_1"]');
    expect(playHtml).toContain('"西风收口": ["ascension_gang_score_plus_1", "ascension_west_tailmark_plus_1", "ascension_west_close_plus_1", "ascension_west_lanternhold_plus_1", "ascension_deadwall_settle_plus_1", "ascension_west_tailpress_plus_1", "ascension_west_tailblade_plus_1", "ascension_west_lanternseal_plus_1", "ascension_west_gatekill_plus_1"]');
    expect(playHtml).toContain('"北风封火": ["ascension_hu_score_plus_1", "ascension_north_lockfire_plus_1", "ascension_north_flarehold_plus_1", "ascension_north_finishfire_plus_1", "ascension_north_lockhold_plus_1", "ascension_north_lockblade_plus_1", "ascension_north_burnseal_plus_1", "ascension_north_coalfire_plus_1"]');
    expect(playHtml).toContain('"ascension_west_lanternseal_plus_1"');
    expect(playHtml).toContain('"ascension_north_coalfire_plus_1"');
    expect(playHtml).toContain('"ascension_west_throatseal_plus_1"');
    expect(playHtml).toContain('"ascension_north_smotherlock_plus_1"');
    expect(playHtml).toContain('"ascension_east_backflow_plus_1"');
    expect(playHtml).toContain('"ascension_south_breathseal_plus_1"');
    expect(playHtml).toContain('"ascension_west_allinlisten_plus_1"');
    expect(playHtml).toContain('"ascension_north_tailvault_plus_1"');
    expect(playHtml).toContain('"steady-hand+trial-sight": ["ascension_east_trace_plus_1", "ascension_east_scout_plus_1", "ascension_east_trailhead_plus_1", "ascension_east_pressureline_plus_1", "ascension_east_pressureweave_plus_1", "ascension_east_backflow_plus_1"]');
    expect(playHtml).toContain('"south-bulkhead+storm-guard": ["ascension_south_bulkhead_wall_plus_1", "ascension_south_wall_plus_1", "ascension_south_breath_plus_1", "ascension_south_breathseal_plus_1"]');
    expect(playHtml).toContain('"trial-sight+late-flare": ["ascension_west_tracefire_plus_1", "ascension_west_signal_plus_1", "ascension_west_focus_plus_1", "ascension_west_variant_plus_1", "ascension_west_flareburst_plus_1", "ascension_west_signalweave_plus_1", "ascension_west_lineburn_plus_1", "ascension_west_allinlisten_plus_1", "ascension_west_linehold_plus_1"]');
    expect(playHtml).toContain('"seal-table+late-flare": ["ascension_north_flarehold_plus_1", "ascension_north_lockfire_plus_1", "ascension_north_finishfire_plus_1", "ascension_north_lockhold_plus_1", "ascension_north_lockblade_plus_1", "ascension_north_tailvault_plus_1"]');
    expect(playHtml).toContain("西风收口·封灯");
    expect(playHtml).toContain("西风构筑：封灯收线");
    expect(playHtml).toContain("北风封火·闷燃");
    expect(playHtml).toContain("北风构筑：闷燃封火");
    expect(playHtml).toContain("西风定口·封喉");
    expect(playHtml).toContain("西风构筑：封喉定口");
    expect(playHtml).toContain("北风封尾·闷锁");
    expect(playHtml).toContain("北风构筑：闷锁封尾");
    expect(playHtml).toContain("const MAINLINE_REWARD_ORDER_BIAS = {");
    expect(playHtml).toContain('13: ["info_vision_plus_1", "tool_mix_supply", "hu_coin_plus_15"]');
    expect(playHtml).toContain('16: ["hu_score_plus_18", "hu_coin_plus_15", "gang_score_plus_25"]');
    expect(playHtml).toContain('19: ["gang_score_plus_25", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(playHtml).toContain("const mainlineLateRewardBias = !isAscensionMode()");
    expect(playHtml).toContain("getThresholdBiasChain(MAINLINE_REWARD_ORDER_BIAS, mainlineOrder)");
    expect(playHtml).not.toContain("先吃到事件线：");
    expect(playHtml).not.toContain("这一轮真正接上的是");
    expect(playHtml).not.toContain("下轮封灯建议：");
    expect(playHtml).not.toContain("下轮闷燃建议：");
    expect(playHtml).not.toContain("下轮封喉建议：");
    expect(playHtml).not.toContain("下轮闷锁建议：");
    expect(playHtml).toContain("南风构筑：挡墙换气");
    expect(playHtml).toContain("南风构筑：缓收蓄口");
    expect(playHtml).toContain("南风构筑：续墙换气");
    expect(playHtml).toContain("南风奖赏：偏门换气");
    expect(playHtml).toContain("南风奖赏：南风挡墙");
    expect(playHtml).toContain("南风构筑：挡墙收口");
    expect(playHtml).toContain("西风奖赏：试炼压线");
    expect(playHtml).toContain("西风奖赏：西风照牌");
    expect(playHtml).toContain("北风构筑：收刀封火");
    expect(playHtml).toContain("北风奖赏：北风固台");
    expect(playHtml).toContain("北风能力：封盘护符");
    expect(playHtml).toContain("北风能力：迟火翻局");
    expect(playHtml).toContain("高阶构筑：封终迟火");
    expect(playHtml).toContain("高阶构筑：护河续押");
    expect(playHtml).toContain("高阶构筑：迟尾缓燃");
    expect(playHtml).toContain("高阶构筑：顺手摸牌");
    expect(playHtml).toContain("高阶构筑：顺手抢胡");
    expect(playHtml).toContain("高阶构筑：滚听续拍");
    expect(playHtml).toContain("高阶构筑：滚听顺胡");
    expect(playHtml).toContain("听成封胡");
    expect(playHtml).toContain("高阶构筑：听成终胡");
    expect(playHtml).toContain("高阶构筑：临门补洞");
    expect(playHtml).toContain("高阶构筑：顺路续拍");
    expect(playHtml).toContain("南风构筑：河道留位");
    expect(playHtml).toContain("南风构筑：护堤对账");
    expect(playHtml).toContain("南风构筑：护堤续押");
    expect(playHtml).toContain("南风构筑：回账续押");
    expect(playHtml).toContain("归账封缺");
    expect(playHtml).toContain("南风构筑：归账封缺");
    expect(playHtml).toContain("西风构筑：看线留口");
    expect(playHtml).toContain("西风构筑：判卷封口");
    expect(playHtml).toContain("西风构筑：封卷落口");
    expect(playHtml).toContain("交卷定判");
    expect(playHtml).toContain("西风构筑：交卷定判");
    expect(playHtml).toContain("西风构筑：锁门收线");
    expect(playHtml).toContain("西风构筑：听刃封胡");
    expect(playHtml).toContain("北风构筑：压潮续航");
    expect(playHtml).toContain("南风构筑：护河留手");
    expect(playHtml).toContain("南风构筑：稳河控口");
    expect(playHtml).toContain("西风构筑：试炼审计");
    expect(playHtml).toContain("西风构筑：终判盖章");
    expect(playHtml).toContain("西风构筑：牌尾留门");
    expect(playHtml).toContain("高阶构筑：总账熄灯");
    expect(playHtml).toContain("灭灯关账");
    expect(playHtml).toContain("高阶构筑：灭灯关账");
    expect(playHtml).toContain("北风构筑：杠潮压顶");
    expect(playHtml).toContain("北风构筑：稳压续命");
    expect(playHtml).toContain("北风构筑：锁墙定命");
    expect(playHtml).toContain("北风构筑：压盘定局");
    expect(playHtml).toContain("北风构筑：定盘续命");
    expect(playHtml).toContain("压底成盘");
    expect(playHtml).toContain("北风构筑：压底成盘");
    expect(playHtml).toContain("北风构筑：封潮收官");
    expect(playHtml).toContain("北风构筑：绝锁封尾");
    expect(playHtml).toContain('"顺手胡流": ["ascension_route_followup_plus_1", "ascension_east_smoothdraw_plus_1", "ascension_east_route_plus_1", "ascension_east_followthrough_plus_1", "ascension_east_followseal_plus_1", "ascension_east_followlock_plus_1", "ascension_east_snaphu_plus_1", "ascension_east_rollstep_plus_1", "ascension_east_rollhu_plus_1"]');
    expect(playHtml).toContain('"顺手胡流·滚听": ["ascension_east_followseal_plus_1", "ascension_east_followlock_plus_1", "ascension_east_snaphu_plus_1", "ascension_east_rollstep_plus_1", "ascension_east_rollhu_plus_1"]');
    expect(playHtml).toContain('"护河续押": ["ascension_river_surge_plus_1", "ascension_south_riverhold_plus_1", "ascension_surge_cache_plus_1", "ascension_south_riverlane_plus_1", "ascension_south_rivercache_plus_1", "ascension_south_rivervault_plus_1", "ascension_south_riverdike_plus_1", "ascension_south_riveraudit_plus_1", "ascension_south_riverledger_plus_1"]');
    expect(playHtml).toContain('"护河续押·回账": ["ascension_south_rivercache_plus_1", "ascension_south_rivervault_plus_1", "ascension_south_riverdike_plus_1", "ascension_south_riveraudit_plus_1", "ascension_south_riverledger_plus_1"]');
    expect(playHtml).toContain('"试炼流": ["ascension_lantern_peek_plus_1", "ascension_west_trialaudit_plus_1", "ascension_west_signal_plus_1", "ascension_west_linehold_plus_1", "ascension_west_triallock_plus_1", "ascension_west_trialverdict_plus_1", "ascension_west_trialgrade_plus_1", "ascension_west_trialstamp_plus_1", "ascension_west_trialseal_plus_1"]');
    expect(playHtml).toContain('"试炼流·封卷": ["ascension_west_triallock_plus_1", "ascension_west_trialverdict_plus_1", "ascension_west_trialgrade_plus_1", "ascension_west_trialstamp_plus_1", "ascension_west_trialseal_plus_1"]');
    expect(playHtml).toContain('"杠流": ["ascension_north_kongtide_plus_1", "ascension_kong_chain_plus_1", "ascension_gang_score_plus_18", "ascension_north_tidehold_plus_1", "ascension_kong_overheat_plus_1"]');
    expect(playHtml).toContain('"稳压流": ["ascension_north_walllife_plus_1", "ascension_rescue_wall_plus_1", "ascension_north_bastion_plus_1", "ascension_north_tidehold_plus_1", "ascension_north_wallroute_plus_1", "ascension_north_wallfallback_plus_1", "ascension_north_counterwall_plus_1", "ascension_north_walllock_plus_1", "ascension_north_wallfinish_plus_1", "ascension_north_wallanchor_plus_1"]');
    expect(playHtml).toContain('"稳压流·定盘": ["ascension_north_wallroute_plus_1", "ascension_north_wallfallback_plus_1", "ascension_north_counterwall_plus_1", "ascension_north_walllock_plus_1", "ascension_north_wallfinish_plus_1", "ascension_north_wallanchor_plus_1"]');
    expect(playHtml).toContain('"顺手胡流": ["顺手胡流", "顺手胡流·扣拍", "顺手胡流·抢胡", "顺手胡流·滚听", "顺手胡流·听成"]');
    expect(playHtml).toContain('"护河续押": ["护河续押", "护河续押·顶库", "护河续押·护堤", "护河续押·回账", "护河续押·归账"]');
    expect(playHtml).toContain('"试炼流": ["试炼流", "试炼流·对卷", "试炼流·判卷", "试炼流·封卷", "试炼流·交卷"]');
    expect(playHtml).toContain('"收官流": ["收官流", "收官流·试口", "收官流·关灯", "收官流·封账", "收官流·熄灯", "收官流·灭灯"]');
    expect(playHtml).toContain('"稳压流": ["稳压流", "稳压流·回墙", "稳压流·反推", "稳压流·锁墙", "稳压流·定盘", "稳压流·压底"]');
    expect(playHtml).toContain('summary: "主攻 胡，靠路线奖励滚雪球。"');
    expect(playHtml).toContain('summary: "主攻 杠/碰，靠护河和续押把中后段拖长。"');
    expect(playHtml).toContain("试炼流要先审清目标口，再把对卷和最后收束落成答卷");
    expect(playHtml).toContain('summary: "主攻 胡/碰，靠牌尾整理后收刀。"');
    expect(playHtml).toContain('summary: "主攻 碰/杠，优先保命和续航。"');
    expect(playHtml).toContain('"西风收口": ["ascension_gang_score_plus_1", "ascension_west_tailmark_plus_1", "ascension_west_close_plus_1", "ascension_west_lanternhold_plus_1", "ascension_deadwall_settle_plus_1", "ascension_west_tailpress_plus_1", "ascension_west_tailblade_plus_1", "ascension_west_lanternseal_plus_1", "ascension_west_gatekill_plus_1"]');
    expect(playHtml).toContain('"西风定口": ["ascension_hu_score_plus_1", "ascension_west_focus_plus_1", "ascension_west_judgeline_plus_1", "ascension_west_accountbook_plus_1", "ascension_west_bladeecho_plus_1", "ascension_west_tailmark_plus_1", "ascension_west_close_plus_1", "ascension_west_tailpress_plus_1", "ascension_west_listenpress_plus_1", "ascension_west_tailblade_plus_1", "ascension_west_listenlock_plus_1", "ascension_west_listenblade_plus_1", "ascension_west_bindcut_plus_1", "ascension_west_bindlisten_plus_1", "ascension_west_bindkill_plus_1", "ascension_west_throatseal_plus_1", "ascension_west_listenkill_plus_1"]');
    expect(playHtml).toContain('"北风锁火": ["ascension_hu_score_plus_1", "ascension_north_lockhold_plus_1", "ascension_north_lockfire_plus_1", "ascension_north_surgeguard_plus_1", "ascension_north_coalwall_plus_1", "ascension_north_finalblade_plus_1", "ascension_north_deadwall_plus_1", "ascension_north_locktower_plus_1", "ascension_north_slowburn_plus_1", "ascension_north_surgepress_plus_1", "ascension_north_surgekill_plus_1", "ascension_north_endseal_plus_1", "ascension_north_extinguish_plus_1", "ascension_north_tideseal_plus_1"]');
    expect(playHtml).toContain('"北风封尾": ["ascension_gang_score_plus_1", "ascension_north_tailhold_plus_1", "ascension_north_finalblade_plus_1", "ascension_north_deadwall_plus_1", "ascension_north_laststand_plus_1", "ascension_north_tailpress_plus_1", "ascension_north_closedoor_plus_1", "ascension_north_breakseal_plus_1", "ascension_north_tailgate_plus_1", "ascension_north_deadlock_plus_1", "ascension_north_smotherlock_plus_1", "ascension_north_totallock_plus_1"]');
    expect(playHtml).toContain("function getAscensionBossTrialPhases");
    expect(playHtml).toContain("function mergeBossGoals");
    expect(playHtml).toContain("function getAscensionBossPack");
    expect(playHtml).toContain("ASCENSION_BOSS_TIER_LABELS");
    expect(playHtml).toContain("东风守路");
    expect(playHtml).toContain("顺手追口");
    expect(playHtml).toContain('`阶段目标：${windName}先围绕 ${buildName} 的 ${comboText} 开线。${bossPack.openingHook} ${tierTargets[ascensionLevel] || tierTargets[1]}`');
    expect(playHtml).toContain("试炼流要先审清目标口，再把对卷和最后收束落成答卷");
    expect(playHtml).toContain('fetch(getConfigAssetUrl("levels.json"))');
    expect(playHtml).toContain('fetch(getConfigAssetUrl("rewards.json"))');
    expect(playHtml).toContain("ascension_east_followseal_plus_1");
    expect(playHtml).toContain("ascension_south_rivercache_plus_1");
    expect(playHtml).toContain("ascension_west_triallock_plus_1");
    expect(playHtml).toContain("ascension_north_wallroute_plus_1");
    expect(playHtml).toContain("高阶构筑：顺手封胡");
    expect(playHtml).toContain("南风构筑：续押补库");
    expect(playHtml).toContain("西风构筑：试压锁口");
    expect(playHtml).toContain("北风构筑：压墙留命");
    expect(playHtml).toContain("护河流");
    expect(playHtml).toContain("续押流");
    expect(playHtml).toContain("缓冲流");
    expect(playHtml).toContain("护河压线");
    expect(playHtml).toContain("续押留手");
    expect(playHtml).toContain("牌尾垫手");
    expect(playHtml).toContain("护河续押");
    expect(playHtml).toContain("迟尾缓燃");
    expect(playHtml).toContain("高阶奖励");
    expect(playHtml).toContain('source: "hulebu-demo-shell"');
  });

  it("支持更完整的局外长期成长参数透传", () => {
    expect(playHtml).toContain("riverBonus");
    expect(playHtml).toContain("coinBonus");
    expect(playHtml).toContain("visionBonus");
    expect(playHtml).toContain("requestedRiverBonus");
    expect(playHtml).toContain("requestedCoinBonus");
    expect(playHtml).toContain("requestedVisionBonus");
    expect(playHtml).toContain("requestedRunArchetype");
    expect(playHtml).toContain("requestedPreferredRoute");
    expect(playHtml).toContain("RUN_ARCHETYPE_CONFIGS");
    expect(playHtml).toContain("model.runArchetype");
    expect(playHtml).toContain("model.shellBonuses.river");
    expect(playHtml).toContain("model.shellBonuses.coin");
    expect(playHtml).toContain("model.shellBonuses.vision");
    expect(playHtml).toContain("model.preferredRoute");
    expect(playHtml).toContain("function getPreferredRouteStartBonus()");
    expect(playHtml).toContain("function getRunArchetypeConfig(archetypeId)");
    expect(playHtml).toContain("function getRunArchetypeRewardPool(levelIndex = model.levelIndex)");
    expect(playHtml).toContain("function getPreferredRouteRewardPool(levelIndex = model.levelIndex)");
    expect(playHtml).toContain("routeMasteryLevel");
    expect(playHtml).toContain("function getRouteMasteryRewardPool()");
    expect(playHtml).toContain("胡流开局：终局兑现更早起势，先补 20 铜钱和胡牌分。");
    expect(playHtml).toContain("信息流开局：先补 2 次看山，把读口先看清。");
    expect(playHtml).toContain("杠流开局：先把杠路热起来，牌河额外 +1。");
    expect(playHtml).toContain("道具流开局：三类整理工具各补 1，先把坏手修回来。");
    expect(playHtml).toContain("preferredRouteBonus?.riverLimit");
    expect(playHtml).toContain("preferredRouteBonus?.reserve");
    expect(playHtml).toContain("preferredRouteBonus?.shields");
    expect(playHtml).toContain("preferredRouteBonus?.coins");
    expect(playHtml).toContain("preferredRouteBonus?.bonuses?.hu");
    expect(playHtml).toContain("preferredRouteBonus?.tools?.vision");
    expect(playHtml).toContain("preferredRouteBonus?.tools?.discard");
    expect(playHtml).toContain("preferredRouteBonus?.tools?.undo");
    expect(playHtml).toContain("tail-lantern");
    expect(playHtml).toContain("old-tile-box");
    expect(playHtml).toContain("risk-double-down");
    expect(playHtml).toContain('12: ["chi_tool_supply", "info_shuffle_plus_1", "hu_coin_plus_15"]');
    expect(playHtml).toContain('15: ["hu_coin_plus_15", "shuffle_plus_1", "tool_mix_supply"]');
    expect(playHtml).toContain("if (routeMasteryLevel <= 0 || !model.preferredRoute) return null;");
    expect(playHtml).toContain('if (model.preferredRoute.includes("河控")) return ["gang_score_plus_25"];');
    expect(playHtml).toContain('if (model.preferredRoute.includes("道具流")) return ["tool_mix_supply"];');
    expect(playHtml).toContain('if (model.preferredRoute.includes("救场")) return ["shield_plus_1"];');
    expect(playHtml).toContain("const archetypeRewardPool = getRunArchetypeRewardPool(levelIndex);");
    expect(playHtml).toContain("const preferredRoutePool = getPreferredRouteRewardPool();");
    expect(playHtml).toContain("preferredRouteBonus?.bonuses?.gang");
    expect(playHtml).toContain("if (routeMasteryLevel < 2) return [];");
    expect(playHtml).toContain("局外偏好第二档轻补一刀");
    expect(playHtml).toContain("model.run.coins = Math.max(0, model.shellBonuses.coin)");
    expect(playHtml).toContain("model.state.riverLimit ?? DEFAULT_RIVER_LIMIT");
    expect(playHtml).toContain("+ model.shellBonuses.river");
    expect(playHtml).toContain("vision: (baseTools.vision ?? 0) + (model.run.tools.vision ?? 0) + model.shellBonuses.vision");
    expect(playHtml).not.toContain("但这把不是先崩在节奏，而是容错墙先被打穿了。");
    expect(playHtml).not.toContain("但这把更先崩在节奏没滚起来。");
    expect(playHtml).not.toContain("不过这把更先崩在 build 没接实，不是容错先断。");
  });

  it("玩家页显示记牌器，供玩家查看剩余花色和数量", () => {
    expect(playHtml).toContain('<section class="section counter-section" aria-label="记牌器">');
    expect(playHtml).toContain("<h2>记牌器</h2>");
    expect(playHtml).toContain("body.play-view .counter-section");
    expect(playHtml).toContain("body.play-view .counts");
    expect(playHtml).toContain('id="huHint"');
    expect(playHtml).toContain(".hu-hint");
    expect(playHtml).toContain("rank-dot has hu-wait");
    expect(playHtml).toContain(".rank-face");
    expect(playHtml).toContain(".rank-count");
    expect(playHtml).toContain('face.className = "rank-face";');
    expect(playHtml).toContain('countLabel.className = "rank-count";');
    expect(playHtml).toContain("countLabel.textContent = String(count);");
    expect(playHtml).toContain("function renderCounts()");
    expect(playHtml).toContain("function renderHuHint()");
    expect(playHtml).toContain("function getHuWaitHint()");
    expect(playHtml).toContain("function getHuWaitTargetKeys()");
    expect(playHtml).toContain("function getRemainingTileCounts()");
    expect(playHtml).toContain('if (tile.location !== "board") continue;');
    expect(playHtml).toContain("counts[tile.suit].total += 1;");
    expect(playHtml).toContain("counts[tile.suit].ranks[tile.rank] += 1;");
  });

  it("试玩 Demo 暴露有限牌河、明牌区和补杠行为入口", () => {
    expect(playHtml).toContain('<section class="section meld-section" aria-label="明牌区">');
    expect(playHtml).toContain('<section class="section river-section" aria-label="牌河">');
    expect(playHtml).toContain('id="openMelds"');
    expect(playHtml).toContain('id="river"');
    expect(playHtml).toContain("riverLimit");
    expect(playHtml).toContain("openMelds");
    expect(playHtml).toContain("discardSelecting");
    expect(playHtml).toContain("function startDiscardSelection()");
    expect(playHtml).toContain("function discardSlotTile");
    expect(playHtml).toContain("function renderRiver()");
    expect(playHtml).toContain("function renderOpenMelds()");
    expect(playHtml).toContain("function getSupplementalGangCandidates");
    expect(playHtml).toContain("function openMountainByAction");
    expect(playHtml).toContain("const KONG_SHAKE_LOOSE_COUNT = 1;");
    expect(playHtml).toContain("const HU_SHAKE_LOOSE_COUNT = 3;");
    expect(playHtml).toContain("openMountainByAction(HU_SHAKE_LOOSE_COUNT)");
    expect(playHtml).toContain("openMountainByAction(KONG_SHAKE_LOOSE_COUNT)");
    expect(playHtml).toContain("looseMountainTile");
    expect(playHtml).toContain("function shakeLooseMountainTile");
    expect(playHtml).toContain("function getLooseMountainPosition");
    expect(playHtml).toContain("bugang");
    expect(playHtml).toContain("补杠");
    expect(playHtml).toContain("胡后清河");
  });

  it("试玩 Demo 暴露残局收官第一阶段入口", () => {
    expect(playHtml).toContain("function resolveLevelClear");
    expect(playHtml).toContain("function shouldEnterEndgameSettlement");
    expect(playHtml).toContain("function showEndgameSettlement");
    expect(playHtml).toContain("function completeEndgameByDiscard");
    expect(playHtml).toContain("function startEndgamePrimerSelection");
    expect(playHtml).toContain("function pickEndgamePrimerTile");
    expect(playHtml).toContain("function applyPendingGuideTileToLevel");
    expect(playHtml).toContain("残局收官");
    expect(playHtml).toContain("弃牌通关");
    expect(playHtml).toContain("选作牌引");
    expect(playHtml).toContain("牌引");
    expect(playHtml).toContain("endgamePrimerSelecting");
    expect(playHtml).toContain("pendingGuideTile");
  });

  it("试玩 Demo 暴露关前特殊事件第一版入口", () => {
    expect(playHtml).toContain("const SPECIAL_EVENT_TRIGGER_LEVELS = [5, 7, 9, 11, 13, 15, 17, 19];");
    expect(playHtml).toContain("const DAILY_SPECIAL_EVENT_TRIGGER_ORDERS = [4, 7, 10, 12, 14, 16, 18, 20];");
    expect(playHtml).toContain("const ASCENSION_SPECIAL_EVENT_TRIGGER_LEVELS = [4, 7, 10, 12, 14, 16, 18, 19];");
    expect(playHtml).toContain("const SPECIAL_EVENT_POOL = [");
    expect(playHtml).toContain("function maybeShowSpecialEventBeforeLevel");
    expect(playHtml).toContain("function showSpecialEventOverlay");
    expect(playHtml).toContain("function chooseSpecialEventOption");
    expect(playHtml).toContain("function applySpecialEventEffect");
    expect(playHtml).toContain("function applyPendingLevelModifier");
    expect(playHtml).toContain("function isToolDisabledByModifier");
    expect(playHtml).toContain("function getActiveLevelModifierText");
    expect(playHtml).toContain("activeLevelModifier");
    expect(playHtml).toContain("pendingLevelModifier");
    expect(playHtml).toContain("pendingSpecialEvent");
    expect(playHtml).toContain("specialEventsSeen");
    expect(playHtml).toContain("function getSpecialEventTriggerPosition(levelIndex)");
    expect(playHtml).toContain("function isEndlessSpecialEventTriggerLayer(layer)");
    expect(playHtml).toContain("if (maybeShowSpecialEventBeforeLevel(model.levelIndex)) return;");
    expect(playHtml).toContain("路遇老雀");
    expect(playHtml).toContain("旧牌匣");
    expect(playHtml).toContain("加注一局");
    expect(playHtml).toContain("暗灯牌局");
    expect(playHtml).toContain("禁洗牌");
    expect(playHtml).toContain("禁透视");
    expect(playHtml).toContain("高压牌山");
    expect(playHtml).toContain("const chapterIndex = Math.floor((layer - ENDLESS_START_LAYER) / 5);");
    expect(playHtml).toContain("chapterStep === 2");
    expect(playHtml).toContain("chapterIndex >= 1 && chapterStep === 4");
    expect(playHtml).toContain("chapterIndex >= 3 && chapterStep === 1");
    expect(playHtml).toContain("chapterIndex >= 5 && chapterStep === 3");
    expect(playHtml).toContain("const ENDLESS_SPECIAL_EVENT_PHASE_BIAS = {");
    expect(playHtml).toContain("const ENDLESS_SPECIAL_EVENT_STEP_BIAS = [");
    expect(playHtml).toContain('7: ["tail-lantern", "west-tail-lock", "north-tail-break"]');
    expect(playHtml).toContain("const ENDLESS_REWARD_STEP_BIAS = {");
    expect(playHtml).toContain('{ minChapter: 4, step: 1, eventIds: ["tail-lantern", "west-tail-lock", "west-throat-seal"] }');
    expect(playHtml).toContain('{ minChapter: 6, step: 3, eventIds: ["north-tail-break", "lantern-peek", "north-coal-burn"] }');
    expect(playHtml).toContain('{ minChapter: 7, step: 4, eventIds: ["west-tail-lock", "north-tail-break", "north-coal-burn"] }');
    expect(playHtml).toContain('4: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain('4: ["hu_score_plus_18", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(playHtml).toContain("...(ENDLESS_REWARD_STEP_BIAS[chapterStep] ?? [])");
    expect(playHtml).toContain("return DAILY_SPECIAL_EVENT_TRIGGER_ORDERS.includes(order)");
    expect(playHtml).toContain("return ASCENSION_SPECIAL_EVENT_TRIGGER_LEVELS.includes(levelIndex)");
    expect(playHtml).toContain("const dailyLateEventBiasMap = {");
    expect(playHtml).toContain('12: ["east-guard-mouth", "old-tile-box"]');
    expect(playHtml).toContain('14: ["route-followup", "risk-double-down"]');
    expect(playHtml).toContain('16: ["south-wall-breathe", "seal-delayed"]');
    expect(playHtml).toContain('18: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(playHtml).toContain('20: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
    expect(playHtml).toContain("const ascensionLateEventBiasMap = {");
    expect(playHtml).toContain('11: ["east-scout-pressure", "old-tile-box"]');
    expect(playHtml).toContain('13: ["route-followup", "risk-double-down"]');
    expect(playHtml).toContain('15: ["south-hold-softseal", "seal-delayed"]');
    expect(playHtml).toContain('17: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(playHtml).toContain('19: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
    expect(playHtml).toContain('20: ["north-tail-break", "north-coal-burn", "west-throat-seal"]');
    expect(playHtml).toContain("const mainlineLateEventBiasMap = {");
    expect(playHtml).toContain('11: ["east-guard-mouth", "old-tile-box"]');
    expect(playHtml).toContain('13: ["route-followup", "risk-double-down"]');
    expect(playHtml).toContain('15: ["south-wall-breathe", "seal-delayed"]');
    expect(playHtml).toContain('17: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(playHtml).toContain('19: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
    expect(playHtml).toContain('13: ["info_vision_plus_1", "tool_mix_supply", "hu_coin_plus_15"]');
    expect(playHtml).toContain('12: ["info_vision_plus_1", "info_shuffle_plus_1", "tool_mix_supply"]');
    expect(playHtml).toContain('14: ["hu_coin_plus_15", "tool_mix_supply", "info_shuffle_plus_1"]');
    expect(playHtml).toContain("function getLatestThresholdBias(biasMap, currentValue)");
    expect(playHtml).not.toContain("Object.entries(dailyLateEventBiasMap).reverse().forEach");
    expect(playHtml).not.toContain("Object.entries(ascensionLateEventBiasMap).reverse().forEach");
  });

  it("试玩 Demo 暴露特殊事件第二版结构", () => {
    expect(playHtml).toContain("const SPECIAL_EVENT_RARITIES =");
    expect(playHtml).toContain("const SPECIAL_EVENT_TAGS =");
    expect(playHtml).toContain("const EVENT_BUILD_LINKS =");
    expect(playHtml).toContain("function getSpecialEventOffer");
    expect(playHtml).toContain("偏向 ${buildLink}");
    expect(playHtml).toContain("前段连手顺路");
    expect(playHtml).toContain("中段挡墙收口");
    expect(playHtml).toContain("后段试锋点火");
    expect(playHtml).toContain("残局封尾压台");
    expect(playHtml).toContain("顺路追胡");
    expect(playHtml).toContain("尾巡定局");
    expect(playHtml).toContain("杠河双响");
    expect(playHtml).toContain("稳压续命");
    expect(playHtml).toContain("function getSpecialEventRarityLabel");
    expect(playHtml).toContain("function getSpecialEventTagText");
    expect(playHtml).toContain("稀有事件");
    expect(playHtml).toContain("构筑联动");
    expect(playHtml).toContain("高阶事件");
    expect(playHtml).toContain("险招翻倍");
    expect(playHtml).toContain("河灯旧约");
    expect(playHtml).toContain("封盘押后");
    expect(playHtml).toContain("灯下探牌");
    expect(playHtml).toContain("尾灯留门");
    expect(playHtml).toContain("顺路追胡");
    expect(playHtml).toContain("西风定口·封喉");
    expect(playHtml).toContain("北风封火·闷燃");
    expect(playHtml).toContain("east-guard-mouth");
    expect(playHtml).toContain("south-wall-breathe");
    expect(playHtml).toContain("west-tail-lock");
    expect(playHtml).toContain("north-tail-break");
    expect(playHtml).toContain("west-throat-seal");
    expect(playHtml).toContain("north-coal-burn");
    expect(playHtml).toContain("const preferredRouteEvent = getPreferredRouteEventBias();");
    expect(playHtml).toContain("if (preferredRouteEvent) pool.unshift(preferredRouteEvent);");
    expect(playHtml).toContain("function getPreferredRouteEventBias()");
    expect(playHtml).not.toContain('if (preferredRoute.includes("胡流")) {');
    expect(playHtml).not.toContain('if (preferredRoute.includes("信息流")) {');
    expect(playHtml).not.toContain('if (preferredRoute.includes("救场")) {');
    expect(playHtml).not.toContain('if (preferredRoute.includes("信息流") || preferredRoute.includes("试锋")) pool.unshift(SPECIAL_EVENT_POOL.find((event) => event.id === "old-tile-box"));');
    expect(playHtml).not.toContain('if (preferredRoute.includes("道具流") || preferredRoute.includes("救场")) pool.unshift(SPECIAL_EVENT_POOL.find((event) => event.id === "old-sparrow"));');
    expect(playHtml).toContain('"西风定口": "后段封喉定口"');
    expect(playHtml).toContain('"北风封火": "终局闷燃封火"');
    expect(playHtml).toContain('17: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(playHtml).toContain('19: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
  });

  it("试玩 Demo 的奖励展示带路线标签", () => {
    expect(playHtml).toContain("reward-route");
    expect(playHtml).toContain("吃流");
    expect(playHtml).toContain("碰流");
    expect(playHtml).toContain("杠流");
    expect(playHtml).toContain("胡流");
    expect(playHtml).toContain("道具流");
    expect(playHtml).toContain("信息流");
  });

  it("默认玩家页压缩 HUD，保证操作区优先留在一屏", () => {
    expect(playHtml).toContain("body.play-view .topbar {");
    expect(playHtml).toContain("display: none;");
    expect(playHtml).toContain("body.play-view .play-hud {");
    expect(playHtml).toContain("grid-template-columns: repeat(5, minmax(0, 1fr));");
    expect(playHtml).toContain("body.play-view .brand span {\n        display: none;");
    expect(playHtml).toContain("grid-template-columns: repeat(4, minmax(0, 1fr));");
    expect(playHtml).toContain("@media (max-width: 640px)");
    expect(playHtml).toContain("body.play-view .counts {\n          grid-template-columns: 1fr;");
    expect(playHtml).toContain("body.play-view .board[data-mode=\"mountain\"]");
    expect(playHtml).toContain("width: min(100%, 330px);");
    expect(playHtml).toContain("body.play-view .tool-button {");
    expect(playHtml).toContain("min-height: 36px;");
    expect(playHtml).toContain("body.play-view .slot-area {");
    expect(playHtml).toContain("margin-bottom: 168px;");
    expect(playHtml).toContain("scroll-margin-bottom: 184px;");
  });

  it("失败状态使用显眼弹层并提供重开入口", () => {
    expect(playHtml).toContain("function failLevel()");
    expect(playHtml).toContain("function showLevelFailed()");
    expect(playHtml).toContain('setRewardOverlayMode("failure");');
    expect(playHtml).toContain('.overlay[data-mode="failure"] .failure-dialog {');
    expect(playHtml).toContain('<div class="failure-dialog">\n        <h2 id="failureTitle">失败</h2>\n        <div class="failure-actions" id="failureActions"></div>\n      </div>');
    expect(playHtml).toContain("view.failureActions.replaceChildren(restart);");
    expect(playHtml).toContain('<button class="primary-button" id="restartButton" type="button">重开</button>');
    expect(playHtml).toContain('restart.textContent = "重开";');
    expect(playHtml).toContain('view.status.textContent = "";');
    expect(playHtml).toContain('renderAll("");');
    expect(playHtml).toContain('emitShellEvent("hulebu:run-failed");');
    expect(playHtml).toContain('view.failureTitle.textContent = "失败";');
    expect(playHtml).not.toContain('return "本关失败";');
    expect(playHtml).not.toContain("重开本关");
    expect(playHtml).not.toContain("specialEventSummary: \"\",");
    expect(playHtml).not.toContain("specialEventMessage: \"\",");
    expect(playHtml).not.toContain("bossReview: null,");
    expect(playHtml).not.toContain("const GENERIC_FAILURE_MESSAGE");
    expect(playHtml).not.toContain("function getBossGoalMissingText()");
    expect(playHtml).not.toContain('summary: result === "completed"');
    expect(playHtml).not.toContain('detail: result === "completed"');
    expect(playHtml).not.toContain("nextAdvice: result === \"completed\"");
    expect(playHtml).not.toContain("phaseTarget: phase.target");
    expect(playHtml).not.toContain("keyGoal: goals.length > 0");
    expect(playHtml).not.toContain("keyMiss: missing.length > 0");
    expect(playHtml).not.toContain('mismatch: isAscensionMode() ? "高阶 Boss 变体" : ""');
    expect(playHtml).not.toContain('<p class="failure-message">');
    expect(playHtml).not.toContain(".failure-message");
    expect(playHtml).not.toContain('<section class="failure-panel">');
  });

  it("高阶失败提示保持简短", () => {
    expect(playHtml).toContain("function getBossReviewPayload(result) {");
    expect(playHtml).toContain('view.status.textContent = "";');
    expect(playHtml).not.toContain("构筑回顾主骨：");
    expect(playHtml).not.toContain("这套本来想怎么赢：");
    expect(playHtml).not.toContain("为什么不是别的轴：");
    expect(playHtml).not.toContain("为什么判成这条先塌轴：");
    expect(playHtml).not.toContain("第一刀补什么：");
    expect(playHtml).not.toContain("复盘读法：");
  });

  it("高阶深路线提供专属链路复盘清单", () => {
    expect(playHtml).not.toContain("失败链路复盘：");
  });

  it("高阶深路线把事件推进链切到各自变体", () => {
    expect(playHtml).toContain('"顺手胡流·滚听": ["顺手胡流·抢胡", "顺手胡流·滚听", "顺手胡流·听成"]');
    expect(playHtml).toContain('"顺手胡流·听成": ["顺手胡流·滚听", "顺手胡流·听成"]');
    expect(playHtml).toContain('"护河续押·回账": ["护河续押·护堤", "护河续押·回账", "护河续押·归账"]');
    expect(playHtml).toContain('"护河续押·归账": ["护河续押·回账", "护河续押·归账"]');
    expect(playHtml).toContain('"试炼流·封卷": ["试炼流·判卷", "试炼流·封卷", "试炼流·交卷"]');
    expect(playHtml).toContain('"试炼流·交卷": ["试炼流·封卷", "试炼流·交卷"]');
    expect(playHtml).toContain('"收官流·熄灯": ["收官流·封账", "收官流·熄灯", "收官流·灭灯"]');
    expect(playHtml).toContain('"收官流·灭灯": ["收官流·熄灯", "收官流·灭灯"]');
    expect(playHtml).toContain('"稳压流·定盘": ["稳压流·锁墙", "稳压流·定盘", "稳压流·压底"]');
    expect(playHtml).toContain('"稳压流·压底": ["稳压流·定盘", "稳压流·压底"]');
  });

  it("每日词缀会直接带自己的重点组合和奖励偏置", () => {
    expect(playHtml).toContain('featuredCombos: ["peng", "gang"]');
    expect(playHtml).toContain('featuredCombos: ["hu", "chi"]');
    expect(playHtml).toContain('featuredCombos: ["gang", "peng"]');
    expect(playHtml).toContain('featuredCombos: ["chi", "hu"]');
    expect(playHtml).toContain("if (dailyMutator?.featuredCombos?.length) return dailyMutator.featuredCombos;");
  });

  it("每日 Boss 会使用独立变体、阶段和目标包", () => {
    expect(playHtml).toContain('"daily-warden": {');
    expect(playHtml).toContain('title: "每日 Boss 变体"');
    expect(playHtml).toContain('label: "今日守关"');
    expect(playHtml).toContain('rewardQuality: "今日"');
    expect(playHtml).toContain("function getDailyBossPack(levelIndex = model.levelIndex)");
    expect(playHtml).toContain('labelSuffix: "河压守关"');
    expect(playHtml).toContain('labelSuffix: "尾巡追击"');
    expect(playHtml).toContain('labelSuffix: "封尾落锁"');
    expect(playHtml).toContain("function getDailyBossTrialPhases(levelIndex = model.levelIndex)");
    expect(playHtml).toContain('if (isDailyMode() && isBossLevel(levelIndex)) return BOSS_TRIAL_VARIANTS["daily-warden"];');
    expect(playHtml).toContain('if (isDailyMode() && isBossLevel(levelIndex)) return getDailyBossTrialPhases(levelIndex);');
    expect(playHtml).toContain('if (isDailyMode() && getActiveBossGoals(model.levelIndex).length > 0) return "每日";');
    expect(playHtml).toContain('title: `${dailyMutator?.label ?? "今日牌局"} Boss 变体`');
    expect(playHtml).toContain('const mutatorFeaturedCombos = isFinalDailyBoss');
    expect(playHtml).toContain('? (mutator?.featuredCombos ?? []).filter((combo) => combo === "hu" || combo === "gang").slice(0, 1)');
    expect(playHtml).toContain(': (mutator?.featuredCombos ?? []).slice(0, 2);');
    expect(playHtml).toContain("const mutatorComboGoals = mutatorFeaturedCombos.map((combo) => ({");
    expect(playHtml).toContain("const normalizedPackBonusGoals = (pack.bonusGoals ?? []).flatMap((goal) => {");
    expect(playHtml).toContain('if (goal.type === "combo_count" && goal.combo !== "hu" && goal.combo !== "gang") return [];');
    expect(playHtml).toContain('if (goal.type === "combo_count" && goal.combo === "gang") {');
    expect(playHtml).toContain('return [{ ...goal, target: 1 }];');
    expect(playHtml).toContain("const isFinalDailyBoss = level.order >= 20;");
    expect(playHtml).toContain('if (isFinalDailyBoss && goal.type === "combo_count" && goal.combo === "peng") {');
    expect(playHtml).toContain('if (isFinalDailyBoss && goal.type === "score_target") {');
    expect(playHtml).toContain('return { ...goal, target: Math.min(goal.target ?? 0, 186) };');
  });

  it("无尽 Boss 和终章 Boss 会使用独立试炼阶段", () => {
    expect(playHtml).toContain("function getEndlessBossPack(levelIndex = model.levelIndex)");
    expect(playHtml).toContain("function getEndlessBossTrialPhases(levelIndex = model.levelIndex)");
    expect(playHtml).toContain('label: "1. 起章"');
    expect(playHtml).toContain('label: "2. 接章"');
    expect(playHtml).toContain('label: "3. 守层"');
    expect(playHtml).toContain('label: "4. 过章"');
    expect(playHtml).toContain("function getFinalBossPack(levelIndex = model.levelIndex)");
    expect(playHtml).toContain("function getFinalBossTrialPhases(levelIndex = model.levelIndex)");
    expect(playHtml).toContain('label: "2. 立轴"');
    expect(playHtml).toContain('label: "3. 压王"');
    expect(playHtml).toContain('label: "4. 斩尾"');
    expect(playHtml).toContain("if (isEndlessMode() && isBossLevel(levelIndex)) return getEndlessBossTrialPhases(levelIndex);");
    expect(playHtml).toContain("if (isFriendDemoFinalBossLevel(levelIndex)) return getFinalBossTrialPhases(levelIndex);");
    expect(playHtml).toContain('title: `${chapterProfile?.label ?? `第 ${chapter} 章`} · ${theme}守层`');
    expect(playHtml).toContain('title: `${FRIEND_DEMO_FINAL_BOSS_TITLE} · ${archetype.label}`');
    expect(playHtml).toContain('const runArchetypeLabel = getRunArchetypeConfig(model.runArchetype).label;');
    expect(playHtml).toContain('focus: `${runArchetypeLabel} · ${finalBossPack?.focusLine ?? variant.focus}`');
    expect(playHtml).not.toContain('focus: `${model.preferredRoute || "当前路线"} · ${finalBossPack?.focusLine ?? variant.focus}`');
    expect(playHtml).toContain('if (goal.type === "combo_count" && goal.combo === "peng") {');
    expect(playHtml).toContain('return { ...goal, target: 1 };');
    expect(playHtml).toContain('return { ...goal, target: Math.min(goal.target ?? 0, 186) };');
    expect(playHtml).toContain("const chapterBossHasGangGoal = (chapterProfile?.bossGoals ?? []).some((goal) => goal.type === \"combo_count\" && goal.combo === \"gang\");");
    expect(playHtml).toContain("const chapterBossComboGoalCount = (chapterProfile?.bossGoals ?? []).filter((goal) => goal.type === \"combo_count\").length;");
    expect(playHtml).toContain("const shouldAddEndlessPengGoal = phase >= 4 && phase < 6 && chapterBossComboGoalCount < 2;");
    expect(playHtml).toContain("const endlessScoreTarget = 164 + chapter * 16;");
    expect(playHtml).toContain('{ type: "combo_count", combo: "gang", target: layer % 10 === 0 && !chapterBossHasGangGoal ? 2 : 1 },');
    expect(playHtml).toContain('if (shouldAddEndlessPengGoal) goals.splice(1, 0, { type: "combo_count", combo: "peng", target: 1 });');
    expect(playHtml).toContain('if (phase === 7 && chapter < 7) goals.push({ type: "combo_count", combo: "chi", target: 1 });');
  });

  it("无尽后段章节会给更厚的章节奖励偏置", () => {
    expect(playHtml).toContain("const ENDLESS_REWARD_PHASE_BIAS = {");
    expect(playHtml).toContain('6: ["gang_score_plus_25", "hu_coin_plus_15", "info_vision_plus_1"]');
    expect(playHtml).toContain('7: ["gang_score_plus_25", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(playHtml).toContain('8: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain('rewardBias: ["gang_score_plus_25", "chi_tool_supply", "info_vision_plus_1", "hu_coin_plus_15"]');
    expect(playHtml).toContain('rewardBias: ["hu_coin_plus_15", "gang_score_plus_25", "tool_mix_supply", "discard_plus_1"]');
    expect(playHtml).toContain('rewardBias: ["hu_score_plus_18", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(playHtml).toContain("...(ENDLESS_REWARD_PHASE_BIAS[chapterProfile?.phase ?? 1] ?? [])");
  });

  it("每日和高阶后段奖励也会跟着事件拍点一起抬高", () => {
    expect(playHtml).toContain("const MAINLINE_REWARD_ORDER_BIAS = {");
    expect(playHtml).toContain('13: ["info_vision_plus_1", "tool_mix_supply", "hu_coin_plus_15"]');
    expect(playHtml).toContain('16: ["hu_score_plus_18", "hu_coin_plus_15", "gang_score_plus_25"]');
    expect(playHtml).toContain('19: ["gang_score_plus_25", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(playHtml).toContain('18: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain("const DAILY_REWARD_ORDER_BIAS = {");
    expect(playHtml).toContain(`const DAILY_REWARD_ORDER_BIAS = {
        12: ["info_vision_plus_1", "info_shuffle_plus_1", "tool_mix_supply"],
        14: ["hu_coin_plus_15", "hu_score_plus_18", "gang_score_plus_25"],
        16: ["hu_coin_plus_15", "info_shuffle_plus_1", "tool_mix_supply"],
        18: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"],
        20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"],
      };`);
    expect(playHtml).toContain('12: ["info_vision_plus_1", "info_shuffle_plus_1", "tool_mix_supply"]');
    expect(playHtml).toContain('14: ["hu_coin_plus_15", "hu_score_plus_18", "gang_score_plus_25"]');
    expect(playHtml).toContain('16: ["hu_coin_plus_15", "info_shuffle_plus_1", "tool_mix_supply"]');
    expect(playHtml).toContain('18: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain("const ASCENSION_REWARD_LEVEL_BIAS = {");
    expect(playHtml).toContain('10: ["info_vision_plus_1", "info_shuffle_plus_1", "hu_coin_plus_15"]');
    expect(playHtml).toContain('14: ["hu_coin_plus_15", "tool_mix_supply", "info_shuffle_plus_1"]');
    expect(playHtml).toContain('16: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain('18: ["hu_coin_plus_15", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).not.toContain('18: ["hu_coin_plus_15", "gang_score_plus_25", "info_vision_plus_1"]');
    expect(playHtml).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(playHtml).toContain("const mainlineLateRewardBias = !isAscensionMode()");
    expect(playHtml).toContain("getThresholdBiasChain(MAINLINE_REWARD_ORDER_BIAS, mainlineOrder)");
    expect(playHtml).toContain("const dailyLateRewardBias = getThresholdBiasChain(DAILY_REWARD_ORDER_BIAS, dailyOrder);");
    expect(playHtml).toContain("...getThresholdBiasChain(ASCENSION_REWARD_LEVEL_BIAS, levelIndex),");
    expect(playHtml).not.toContain("Object.entries(MAINLINE_REWARD_ORDER_BIAS).reduce");
    expect(playHtml).not.toContain("Object.entries(DAILY_REWARD_ORDER_BIAS).reduce");
    expect(playHtml).not.toContain("Object.entries(ASCENSION_REWARD_LEVEL_BIAS).reduce");
  });

  it("每日和高阶奖励池会真正走各自的后段偏置分支", () => {
    expect(playHtml).toContain("if (isDailyMode()) {");
    expect(playHtml).toContain("if (isAscensionMode()) {");
    expect(playHtml).toContain("function getThresholdBiasChain(biasMap, currentValue)");
    expect(playHtml).toContain("return getFriendDemoRewardPool(model.levelIndex);");
    expect(playHtml).toContain('20: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
    expect(playHtml).not.toContain('return (isFriendDemoMode() || isEndlessMode()) ? getFriendDemoRewardPool(model.levelIndex) : currentLevel().rewardPool;');
  });

  it("继续收每日终局和无尽后段 Boss 的额外挂目标", () => {
    expect(playHtml).toContain('filter((combo) => combo === "hu" || combo === "gang").slice(0, 1)');
    expect(playHtml).toContain("...normalizedPackBonusGoals,");
    expect(playHtml).toContain("const chapterBossComboGoalCount = (chapterProfile?.bossGoals ?? []).filter((goal) => goal.type === \"combo_count\").length;");
    expect(playHtml).toContain("const shouldAddEndlessPengGoal = phase >= 4 && phase < 6 && chapterBossComboGoalCount < 2;");
    expect(playHtml).toContain("const endlessScoreTarget = 164 + chapter * 16;");
    expect(playHtml).toContain("if (shouldAddEndlessPengGoal) goals.splice(1, 0, { type: \"combo_count\", combo: \"peng\", target: 1 });");
  });

  it("后半程本局流派会主导奖励，局外基础偏好池只轻补一张", () => {
    expect(playHtml).toContain("const LATE_ROUTE_REWARD_BIAS = {");
    expect(playHtml).toContain('"胡流": ["hu_score_plus_18", "hu_coin_plus_15", "gang_score_plus_25"]');
    expect(playHtml).toContain('"信息流": ["info_vision_plus_1", "info_shuffle_plus_1", "hu_score_plus_18"]');
    expect(playHtml).toContain('"河控流": ["gang_score_plus_25", "chi_tool_supply", "hu_coin_plus_15"]');
    expect(playHtml).toContain('"道具流": ["tool_mix_supply", "discard_plus_1", "shuffle_plus_1"]');
    expect(playHtml).toContain('"救场流": ["reserve_plus_1", "shield_plus_1", "discard_plus_1"]');
    expect(playHtml).toContain("function getPreferredRouteLateRewardBias(levelIndex = model.levelIndex)");
    expect(playHtml).toContain("function getLateRouteBiasForLabel(label, levelIndex = model.levelIndex)");
    expect(playHtml).toContain("const archetypeRewardPool = getRunArchetypeRewardPool(levelIndex);");
    expect(playHtml).toContain("const preferredRoutePool = getPreferredRouteRewardPool();");
    expect(playHtml).toContain('if ((chapterProfile?.chapter ?? 0) < 4) return [];');
    expect(playHtml).toContain("if (dailyOrder < 12) return [];");
    expect(playHtml).toContain("if (levelIndex < 10) return [];");
    expect(playHtml).toContain("if (mainlineOrder < 13) return [];");
    expect(playHtml).not.toContain("const lateBias = routeMasteryLevel >= 2 ? getPreferredRouteLateRewardBias(levelIndex).slice(0, 1) : [];");
    expect(playHtml).not.toContain('if (model.preferredRoute.includes("胡流")) return ["hu_coin_plus_15", ...lateBias];');
    expect(playHtml).not.toContain('if (model.preferredRoute.includes("信息流")) return ["info_vision_plus_1", ...lateBias];');
    expect(playHtml).not.toContain('if (model.preferredRoute.includes("河控")) return ["gang_score_plus_25", ...lateBias];');
  });

  it("失败和奖励弹层层级高于密集牌山所有牌", () => {
    expect(playHtml).toContain("const TILE_Z_INDEX_BASE = 10;");
    expect(playHtml).toContain("const OVERLAY_Z_INDEX = 1000000;");
    expect(playHtml).toContain('document.documentElement?.style?.setProperty("--overlay-z", String(OVERLAY_Z_INDEX));');
    expect(playHtml).toContain("z-index: var(--overlay-z);");
    expect(playHtml).toContain("button.style.zIndex = String(TILE_Z_INDEX_BASE + visual.order);");
  });
});
