export const HULEBU_V3_UI_VERSION = "hulebu-component-pack-v3";

const base = "ui/hulebu";
const sprite = (path: string): string => `${base}/${path}/spriteFrame`;

export const HULEBU_V3_UI_SPRITES = {
  t291: {
    loginWechat: sprite("t291/login-wechat-normal"),
    loginGuest: sprite("t291/login-guest-normal"),
    loginStatus: sprite("t291/login-status-panel"),
    wechatIcon: sprite("t291/icon-wechat"),
    cloudSyncIcon: sprite("t291/icon-cloud-sync"),
    loginErrorIcon: sprite("t291/icon-login-error"),
    loadingSpinner: sprite("t291/loading-spinner-sheet"),
    mascotPedestal: sprite("t291/mascot-login-pedestal"),
    bubbleLeft: sprite("t291/speech-bubble-left"),
    bubbleRight: sprite("t291/speech-bubble-right"),
    bubbleTop: sprite("t291/speech-bubble-top"),
    bubbleWarning: sprite("t291/speech-bubble-warning"),
    bubbleSuccess: sprite("t291/speech-bubble-success"),
    lobbyMainline: sprite("t291/lobby-entry-mainline"),
    lobbyModes: sprite("t291/lobby-entry-modes"),
    lobbyCollection: sprite("t291/lobby-entry-collection"),
    lobbyGrowth: sprite("t291/lobby-entry-growth"),
    modeCollection: sprite("t291/mode-collection"),
    lobbyContinue: sprite("t291/lobby-continue-panel"),
    nodeCurrent: sprite("t291/node-current"),
    nodeLocked: sprite("t291/node-locked"),
    starEmpty: sprite("t291/star-empty"),
    starFilled: sprite("t291/star-filled"),
    chapterSwitch: sprite("t291/chapter-switch-frame"),
    resultVictory: sprite("t291/result-title-victory"),
    resultFailure: sprite("t291/result-title-failure"),
    resultSuggestion: sprite("t291/result-suggestion-panel"),
    resultUnlock: sprite("t291/result-unlock-ribbon"),
    rewardTitle: sprite("t291/reward-title-panel"),
    eventTitle: sprite("t291/event-title-panel"),
    states: {
      loginWechatPressed: sprite("t291/states/login-wechat-pressed"),
      loginWechatDisabled: sprite("t291/states/login-wechat-disabled"),
      loginGuestPressed: sprite("t291/states/login-guest-pressed"),
      actionChiPressed: sprite("t291/states/action-chi-pressed"),
      actionChiDisabled: sprite("t291/states/action-chi-disabled"),
      actionPengPressed: sprite("t291/states/action-peng-pressed"),
      actionPengDisabled: sprite("t291/states/action-peng-disabled"),
      actionGangPressed: sprite("t291/states/action-gang-pressed"),
      actionGangDisabled: sprite("t291/states/action-gang-disabled"),
      actionBugangPressed: sprite("t291/states/action-bugang-pressed"),
      actionBugangDisabled: sprite("t291/states/action-bugang-disabled"),
      actionHuPressed: sprite("t291/states/action-hu-pressed"),
      actionHuDisabled: sprite("t291/states/action-hu-disabled"),
      toolShuffleDisabled: sprite("t291/states/tool-shuffle-disabled"),
      toolUndoDisabled: sprite("t291/states/tool-undo-disabled"),
      toolVisionDisabled: sprite("t291/states/tool-vision-disabled"),
      toolDiscardDisabled: sprite("t291/states/tool-discard-disabled"),
    },
  },
  backgrounds: {
    titleLobby: sprite("backgrounds/title-lobby"),
    map: sprite("backgrounds/map"),
    gameplay: sprite("backgrounds/gameplay"),
    result: sprite("backgrounds/result"),
    loading: sprite("backgrounds/loading"),
  },
  actions: {
    chi: sprite("component-pack-v3/actions/action-chi"),
    peng: sprite("component-pack-v3/actions/action-peng"),
    gang: sprite("component-pack-v3/actions/action-gang"),
    bugang: sprite("component-pack-v3/actions/action-bugang"),
    hu: sprite("component-pack-v3/actions/action-hu"),
  },
  buttons: {
    confirm: sprite("component-pack-v3/buttons/btn-confirm"),
    cancel: sprite("component-pack-v3/buttons/btn-cancel"),
    close: sprite("component-pack-v3/buttons/btn-close"),
    back: sprite("component-pack-v3/buttons/btn-back"),
  },
  hud: {
    level: sprite("component-pack-v3/hud/hud-level"),
    score: sprite("component-pack-v3/hud/hud-score"),
    remaining: sprite("component-pack-v3/hud/hud-remaining"),
    boss: sprite("component-pack-v3/hud/hud-boss"),
    bossHealth: sprite("component-pack-v3/hud/boss-health-bar"),
    counterPanel: sprite("component-pack-v3/hud/counter-panel"),
    counterToggle: sprite("component-pack-v3/hud/counter-toggle"),
    currency: sprite("component-pack-v3/hud/currency-plaque"),
    starProgress: sprite("component-pack-v3/hud/star-progress"),
  },
  panels: {
    comboChoice: sprite("component-pack-v3/panels/combo-choice-panel"),
    discardRescue: sprite("component-pack-v3/panels/discard-rescue-panel"),
    pause: sprite("component-pack-v3/panels/pause-panel"),
    settings: sprite("component-pack-v3/panels/settings-panel"),
    resultStats: sprite("component-pack-v3/panels/result-stats-panel"),
    bottomNav: sprite("component-pack-v3/panels/bottom-nav-frame"),
  },
  cards: {
    archetype: sprite("component-pack-v3/cards/archetype-card"),
    event: sprite("component-pack-v3/cards/event-card"),
    reward: sprite("component-pack-v3/cards/reward-card"),
    upgrade: sprite("component-pack-v3/cards/upgrade-card"),
    mode: sprite("component-pack-v3/cards/mode-card"),
  },
  map: {
    chapterPlaque: sprite("component-pack-v3/map/chapter-plaque"),
    levelNode: sprite("component-pack-v3/map/level-node"),
    normal: sprite("component-pack-v3/map/node-normal"),
    event: sprite("component-pack-v3/map/node-event"),
    reward: sprite("component-pack-v3/map/node-reward"),
    boss: sprite("component-pack-v3/map/node-boss"),
    pathSegment: sprite("component-pack-v3/map/path-segment"),
  },
  modes: {
    mainline: sprite("component-pack-v3/modes/mode-mainline"),
    endless: sprite("component-pack-v3/modes/mode-endless"),
    daily: sprite("component-pack-v3/modes/mode-daily"),
    advanced: sprite("component-pack-v3/modes/mode-advanced"),
  },
  icons: {
    coin: sprite("component-pack-v3/icons/icon-coin"),
    star: sprite("component-pack-v3/icons/icon-star"),
    amulet: sprite("component-pack-v3/icons/icon-amulet"),
  },
  playfield: {
    handSlot: sprite("component-pack-v3/playfield/hand-slot"),
    meldPool: sprite("component-pack-v3/playfield/meld-pool-panel"),
    looseDropZone: sprite("component-pack-v3/playfield/loose-drop-zone"),
  },
  tools: {
    shuffle: sprite("component-pack-v3/tools/tool-shuffle"),
    undo: sprite("component-pack-v3/tools/tool-undo"),
    vision: sprite("component-pack-v3/tools/tool-vision"),
    discard: sprite("component-pack-v3/tools/tool-discard"),
  },
  mascot: {
    idle: sprite("component-pack-v3/mascot/mascot-idle"),
    happy: sprite("component-pack-v3/mascot/mascot-happy"),
    think: sprite("component-pack-v3/mascot/mascot-think"),
    failed: sprite("component-pack-v3/mascot/mascot-failed"),
    guide: sprite("component-pack-v3/mascot/mascot-guide"),
    avatarFrame: sprite("component-pack-v3/mascot/avatar-frame"),
  },
  misc: {
    titleBrand: sprite("component-pack-v3/misc/title-brand"),
    toast: sprite("component-pack-v3/misc/toast-banner"),
    rewardTag: sprite("component-pack-v3/misc/tag-reward"),
    riskTag: sprite("component-pack-v3/misc/tag-risk"),
    victorySeal: sprite("component-pack-v3/misc/victory-seal"),
    failureSeal: sprite("component-pack-v3/misc/failure-seal"),
    tutorialFrame: sprite("component-pack-v3/misc/tutorial-highlight-frame"),
  },
} as const;

export function getHulebuV3TileSpritePath(fileName: string): string {
  return sprite(`tiles-v3/${fileName}`);
}
