import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../../..");

function readWebFile(relativePath: string) {
  return readFileSync(path.join(webRoot, relativePath), "utf8");
}

describe("hulebu web game publishing", () => {
  it("exposes a Next.js game route with an outer shell around the static demo", () => {
    const route = readWebFile("src/app/games/hulebu/page.tsx");
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");
    const demo = readWebFile("public/games/hulebu-demo/index.html");

    expect(route).toContain("HulebuGamePage");
    expect(component).toContain('"use client"');
    expect(component).toContain("/games/hulebu-demo/index.html");
    expect(component).toContain('embed: "shell"');
    expect(component).toContain("开始挑战");
    expect(component).toContain("继续本轮");
    expect(component).toContain("升级");
    expect(component).toContain("无尽");
    expect(component).toContain("每日");
    expect(component).toContain("高阶");
    expect(component).toContain("reserveBonus");
    expect(component).toContain("shieldBonus");
    expect(component).toContain("toolBonus");
    expect(component).toContain("riverBonus");
    expect(component).toContain("coinBonus");
    expect(component).toContain("visionBonus");
    expect(component).toContain("RUN_ARCHETYPES");
    expect(component).toContain("selectedRunArchetype");
    expect(component).toContain("startRunWithArchetype");
    expect(component).toContain("runArchetype");
    expect(component).toContain("preferredRoute");
    expect(component).toContain("routeMasteryLevel");
    expect(component).toContain("bestEndlessLayer");
    expect(component).toContain("dailyBestLevels");
    expect(component).toContain("achievements");
    expect(component).toContain("equippedAscensionLoadout");
    expect(component).toContain("unlockedAscensionPerks");
    expect(demo).toContain('setRewardOverlayMode("failure");');
    expect(demo).toContain("view.failureActions.replaceChildren(restart);");
  });

  it("publishes the current playable HTML demo as static web assets", () => {
    const demo = readWebFile("public/games/hulebu-demo/index.html");
    const tuner = readWebFile("public/games/hulebu-demo/tuner.html");

    expect(demo).toContain("<title>胡了卜玩家试玩</title>");
    expect(demo).toContain('<body class="play-view" data-prototype-view="play">');
    expect(demo).toContain('href="./tuner.html"');
    expect(demo).toContain("function getConfigAssetUrl(filename)");
    expect(demo).toContain('fetch(getConfigAssetUrl("levels.json"))');
    expect(demo).toContain('fetch(getConfigAssetUrl("rewards.json"))');
    expect(demo).toContain("embed-shell");
    expect(demo).toContain('source: "hulebu-demo-shell"');
    expect(demo).toContain("hulebu:run-progress");
    expect(demo).toContain("hulebu:run-complete");
    expect(demo).toContain("hulebu:run-failed");
    expect(demo).toContain("function isEndlessMode()");
    expect(demo).toContain("function isDailyMode()");
    expect(demo).toContain("function getDailyDifficultyProfile");
    expect(demo).toContain("function getEndlessChapterProfile");
    expect(demo).toContain("function getSpecialEventOffer");
    expect(demo).toContain("ENDLESS_START_LAYER = 21");
    expect(demo).toContain("每日牌局");
    expect(demo).toContain("高阶周目");
    expect(demo).toContain("高阶能力");
    expect(demo).toContain("高阶奖励");
    expect(demo).toContain("东风场");
    expect(demo).toContain("南风场");
    expect(demo).toContain("西风场");
    expect(demo).toContain("北风场");
    expect(demo).toContain("今日词缀");
    expect(demo).toContain("今日奖励");
    expect(demo).toContain("dailyParticipationStreak");
    expect(demo).toContain("dailyStreak: isDailyMode() ? getDailyParticipationStreak() : null");
    expect(demo).toContain("章节 Boss");
    expect(demo).toContain("reward-route");
    expect(demo).toContain("胡流");
    expect(demo).toContain("信息流");
    expect(demo).toContain("吃流");
    expect(demo).toContain("道具流");
    expect(demo).toContain("SPECIAL_EVENT_RARITIES");
    expect(demo).toContain("SPECIAL_EVENT_TAGS");
    expect(demo).toContain("EVENT_BUILD_LINKS");
    expect(demo).toContain("稀有事件");
    expect(demo).toContain("构筑联动");
    expect(demo).toContain("高阶事件");
    expect(demo).toContain('const UI_SKIN_ASSET_ROOT = "./assets/ui-v6";');
    expect(demo).toContain("function appendTileFace");
    expect(demo).toContain("function appendTileMiniFace");
    expect(demo).toContain("function getTileAssetUrl");
    expect(demo).toContain('button.dataset.uiSkin = UI_SKIN_VERSION;');
    expect(demo).toContain('button.dataset.uiSkin = comboButtonAssetUrl ? UI_SKIN_VERSION : "text";');
    expect(demo).toContain('hu: "action_hu"');
    expect(demo).toContain(".slot-cell.filled .tile-face-image");
    expect(demo).toContain("border-color: rgba(213, 154, 47, 0.34);");
    expect(demo).toContain("getComboButtonAssetUrl(type, typeCandidates.length > 0)");
    expect(demo).toContain("applyToolButtonSkins();");
    expect(demo).toContain('COMBO_BUTTON_ASSETS[type]');
    expect(demo).not.toContain('hu: "action_gang"');
    expect(demo).toContain('tileList.className = "candidate-tiles";');
    expect(demo).toContain("appendTileMiniFace(tileCell, tile);");
    expect(demo).toContain("appendTileMiniFace(face, { suit, rank });");
    expect(tuner).toContain("<title>胡了卜调牌器</title>");
    expect(readWebFile("public/games/hulebu-demo/config/levels.json")).toContain('"displayName": "胡了卜"');
    expect(readWebFile("public/games/hulebu-demo/config/rewards.json")).toContain('"rewards"');
  });

  it("ships the transparent UI skin assets beside the static demo", () => {
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/buttons/combo/action_chi_normal.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/buttons/combo/action_chi_fire.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/buttons/combo/action_hu_normal.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/buttons/combo/action_hu_fire.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/buttons/tools/tool_shuffle.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/slots/hand_slots_8.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/tiles/mahjong/wan/tile_wan_01.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/tiles/mahjong/bamboo/tile_bamboo_01.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/tiles/mahjong/dot/tile_dot_01.png").length).toBeGreaterThan(100);
    expect(readWebFile("public/games/hulebu-demo/assets/ui-v6/tiles/mahjong/honor/tile_honor_east.png").length).toBeGreaterThan(100);
  });

  it("links the games station and search entry to the playable page", () => {
    const portalData = readWebFile("src/components/portal-data.ts");
    const appHeader = readWebFile("src/components/AppHeader.tsx");

    expect(portalData).toContain('href: "/games/hulebu"');
    expect(portalData).toContain('href: "/games/hulebu",\n    icon: "M"');
    expect(appHeader).toContain('pathname.startsWith("/games/hulebu")');
  });

  it("keeps failure copy minimal in the published demo", () => {
    const demo = readWebFile("public/games/hulebu-demo/index.html");
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");
    const styles = readWebFile("src/modules/games/hulebu/HulebuGamePage.module.css");

    expect(demo).toContain("function failLevel() {");
    expect(demo).toContain("showLevelFailed();");
    expect(demo).toContain("function showLevelFailed() {");
    expect(demo).toContain('renderAll("");');
    expect(demo).toContain('view.runComplete.innerHTML = "";');
    expect(demo).toContain('view.runComplete.classList.remove("show");');
    expect(demo).toContain('data-mode="reward"');
    expect(demo).toContain('.overlay[data-mode="failure"] .failure-dialog');
    expect(demo).toContain('<div class="failure-dialog">');
    expect(demo).toContain('<div class="failure-dialog">\n        <h2 id="failureTitle">失败</h2>\n        <div class="failure-actions" id="failureActions"></div>\n      </div>');
    expect(demo).toContain('setRewardOverlayMode("failure");');
    expect(demo).toContain('view.rewardOverlay.setAttribute("aria-labelledby", mode === "failure" ? "failureTitle" : "rewardTitle");');
    expect(demo).toContain("view.failureActions.replaceChildren(restart);");
    expect(demo).toContain('width: min(168px, calc(100% - 32px));');
    expect(demo).toContain(".failure-actions {\n        display: grid;\n        gap: 0;");
    expect(demo).toContain('<button class="primary-button" id="restartButton" type="button">重开</button>');
    expect(demo).toContain('restart.textContent = "重开";');
    expect(demo).toContain('view.failureTitle.textContent = "失败";');
    expect(demo).toContain('view.status.textContent = "";');
    expect(demo).toContain('emitShellEvent("hulebu:run-failed");');
    expect(demo).not.toContain('return "本关失败";');
    expect(demo).not.toContain("重开本关");
    expect(demo).not.toContain('specialEventSummary: "",');
    expect(demo).not.toContain('specialEventMessage: "",');
    expect(demo).not.toContain("bossReview: null,");
    expect(component).toContain("const visibleSettlement = lastSettlement;");
    expect(component).toContain("function normalizeCompletedSettlement");
    expect(component).toContain('if (settlement.result && settlement.result !== "completed") return null;');
    expect(component).toContain('result: "completed"');
    expect(component).not.toContain("failed?: boolean;");
    expect(component).not.toContain('result?: "completed" | "failed";');
    expect(component).not.toContain("settlement.failed === true");
    expect(component).not.toContain('settlement.result === "failed"');
    expect(component).not.toContain("/失败|结束了/.test(summary)");
    expect(component).toContain("{activeRun ? (");
    expect(demo).not.toContain(".reward-review-card");
    expect(demo).not.toContain(".reward-review-kicker");
    expect(demo).not.toContain(".reward-review-list");
    expect(demo).not.toContain("function getAscensionFailureAnalysis()");
    expect(demo).not.toContain("function getAscensionRunSuggestions()");
    expect(demo).not.toContain("关键失误：");
    expect(demo).not.toContain("构筑回顾主骨：");
    expect(demo).not.toContain("这套本来想怎么赢：");
    expect(demo).not.toContain("为什么不是别的轴：");
    expect(demo).not.toContain("为什么判成这条先塌轴：");
    expect(demo).not.toContain("第一刀补什么：");
    expect(demo).not.toContain("复盘读法：");
    expect(demo).not.toContain("失败链路复盘：");
    expect(demo).not.toContain("牌山已清空，但 Boss 目标未完成：");
    expect(demo).not.toContain("当前卡在 ");
    expect(demo).not.toContain("Boss 复盘");
    expect(demo).not.toContain("下一轮建议：");
    expect(demo).not.toContain('summary: result === "completed"');
    expect(demo).not.toContain('detail: result === "completed"');
    expect(demo).not.toContain("nextAdvice: result === \"completed\"");
    expect(demo).not.toContain("phaseTarget: phase.target");
    expect(demo).not.toContain("keyGoal: goals.length > 0");
    expect(demo).not.toContain("keyMiss: missing.length > 0");
    expect(demo).not.toContain('mismatch: isAscensionMode() ? "高阶 Boss 变体" : ""');
    expect(demo).not.toContain('function failLevel(reason, statusMessage = "本关失败")');
    expect(demo).not.toContain('function showLevelFailed(reason, statusMessage = "本关失败")');
    expect(demo).not.toContain('failLevel(getBossGoalMissingText(), "目标未完成");');
    expect(demo).not.toContain('failLevel("主槽已满，且当前没有可发动的组合，牌河也已满。");');
    expect(demo).not.toContain("const GENERIC_FAILURE_MESSAGE");
    expect(demo).not.toContain("function getBossGoalMissingText()");
    expect(demo).not.toContain('<section class="failure-panel">');
    expect(demo).not.toContain('<p class="failure-message">');
    expect(demo).not.toContain(".failure-message");
    expect(component).not.toContain('<p className={styles.resultDescription}>{FAILURE_SETTLEMENT_SUMMARY}</p>');
    expect(component).not.toContain('summary: isFailureMessage ? "这一轮结束了。"');
    expect(component).not.toContain('? "这一轮结束了。"');
    expect(component).not.toContain('latestSummary: "失败"');
    expect(component).not.toContain("failed:");
    expect(component).not.toContain("debugSettlement");
    expect(component).not.toContain('"本轮失败"');
    expect(component).not.toContain('aria-label="最近事件"');
    expect(component).not.toContain('{visibleSettlement.routeDirection ? <p>{`本轮路线：${visibleSettlement.routeDirection}`}</p> : null}');
    expect(component).not.toContain('<p className={styles.resultSummary}>{visibleSettlement.summary}</p>');
    expect(component).not.toContain("结算 +{visibleSettlement.coinsEarned} 铜钱，局外累计 {visibleSettlement.bankedCoins}。");
    expect(component).not.toContain("settlementReviewCard");
    expect(styles).not.toContain(".settlementReview");
    expect(styles).not.toContain(".settlementReviewGrid");
    expect(styles).not.toContain(".settlementReviewCard");
    expect(styles).not.toContain(".resultSummary");
    expect(demo).not.toContain("view.rewardTitle.textContent = GENERIC_FAILURE_MESSAGE");
    expect(demo).not.toContain("view.runComplete.replaceChildren(restart);");
    expect(demo).not.toContain('.overlay[data-mode="failure"] .reward-title {');
    expect(demo).toContain('restart.className = "primary-button";');
  });

  it("keeps failed runs inside the playable shell instead of opening the outer settlement page", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");

    expect(component).toContain('if (data.type === "hulebu:run-failed") {');
    expect(component).toContain("setActiveRun(null);");
    expect(component).toContain("setLastSettlement(null);");
    expect(component).toContain('setScreen("playing");');
    expect(component).toContain('if (settlement.result && settlement.result !== "completed") return null;');
    expect(component).toContain('result: "completed"');
    expect(component).toContain("normalizeCompletedSettlement(persisted.lastSettlement)");
    expect(component).toContain('screen === "settlement" && visibleSettlement');
    expect(component).toContain("return;");
    expect(component).not.toContain('result === "failed" ? null : lastSettlement');
  });

  it("adds run archetype selection before entering a run", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");

    expect(component).toContain('type RunArchetypeId = "chi" | "peng" | "gang" | "hu" | "tool" | "vision";');
    expect(component).toContain("const RUN_ARCHETYPES: RunArchetypeConfig[] = [");
    expect(component).toContain("const [selectedRunArchetype, setSelectedRunArchetype] = useState<RunArchetypeId>(");
    expect(component).toContain("function startRunWithArchetype");
    expect(component).toContain('aria-label="局内流派"');
    expect(component).toContain("本局主轴");
    expect(component).toContain("起手加成");
    expect(component).toContain("奖励偏置");
    expect(component).toContain('runArchetype: archetypeId');
    expect(component).toContain("长期强度靠局外，这一局真正怎么打，在开局前这里定。局外偏好只轻补一刀。");
    expect(component).toContain("RUN_ARCHETYPE_UNLOCKS");
    expect(component).toContain("getRunArchetypeAvailability");
    expect(component).toContain("前 20 关推荐");
    expect(component).toContain("20 关后自由选择");
    expect(component).toContain('aria-label="局外偏好"');
    expect(component).toContain("自动偏好 · 救场流");
    expect(component).not.toContain("自动挂载");
  });

  it("persists an unfinished run so refresh can resume at the current level", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");

    expect(component).toContain("type ActiveRunResumeState =");
    expect(component).toContain("activeRun: ActiveRunResumeState | null;");
    expect(component).toContain("function restoreActiveRunFromPersistedState");
    expect(component).toContain("resumeLevelOrder?: number");
    expect(component).toContain('params.set("level", String(resumeLevelOrder));');
    expect(component).toContain("resumeEndlessLayer?: number");
    expect(component).toContain('startLayer: String(resumeEndlessLayer ?? ENDLESS_START_LAYER)');
    expect(component).toContain("activeRun: activeRun ? toActiveRunResumeState(activeRun) : null");
    expect(component).toContain("const restoredActiveRun = restoreActiveRunFromPersistedState(persisted, persisted.upgrades, persisted.selectedRouteFocus);");
    expect(component).toContain("setActiveRun(restoredActiveRun);");
    expect(component).toContain('if (restoredActiveRun) setScreen("playing");');
    expect(component).toContain('if (restoredRemoteActiveRun) setScreen("playing");');
    expect(component).toContain("{activeRun ? (");
    expect(component).toContain("onClick={continueRun}");
    expect(component).toContain("继续本轮");
    expect(component).toContain("新开一轮");
  });

  it("syncs the unfinished run snapshot to signed-in account progress", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");
    const accountProgress = readWebFile("src/lib/account/hulebu-progress.ts");
    const progressRoute = readWebFile("src/app/api/games/hulebu/progress/route.ts");
    const prismaSchema = readWebFile("prisma/schema.prisma");
    const migration = readWebFile("prisma/migrations/20260627103000_add_hulebu_active_run/migration.sql");

    expect(prismaSchema).toContain("activeRun          Json?");
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS "activeRun" JSONB;');
    expect(accountProgress).toContain("activeRun: Record<string, unknown> | null;");
    expect(accountProgress).toContain("function sanitizeActiveRun");
    expect(accountProgress).toContain("activeRun: sanitizeActiveRun(input?.activeRun)");
    expect(accountProgress).toContain('Object.prototype.hasOwnProperty.call(localProgress ?? {}, "activeRun")');
    expect(accountProgress).toContain("activeRun: hasIncomingActiveRun ? local.activeRun : pickLatestActiveRun(account.activeRun, local.activeRun)");
    expect(accountProgress).toContain("activeRun: progress.activeRun as Record<string, unknown> | null");
    expect(progressRoute).toContain("activeRun?: Record<string, unknown> | null;");
    expect(component).toContain('"activeRun"');
    expect(component).toContain("activeRun: sanitizeActiveRunResume(payload.activeRun)");
    expect(component).toContain("activeRun: state.activeRun");
    expect(component).toContain("function chooseLatestActiveRunResume");
    expect(component).toContain("const mergedActiveRun = chooseLatestActiveRunResume(local.activeRun, result.data.activeRun);");
    expect(component).toContain("const restoredRemoteActiveRun = restoreActiveRunFromPersistedState(");
    expect(component).toContain("updatedAt: new Date().toISOString()");
  });

  it("publishes route-specific progression chains in the demo", () => {
    const demo = readWebFile("public/games/hulebu-demo/index.html");

    expect(demo).toContain('"顺手胡流·滚听": ["顺手胡流·抢胡", "顺手胡流·滚听", "顺手胡流·听成"]');
    expect(demo).toContain('"护河续押·回账": ["护河续押·护堤", "护河续押·回账", "护河续押·归账"]');
    expect(demo).toContain('"试炼流·封卷": ["试炼流·判卷", "试炼流·封卷", "试炼流·交卷"]');
    expect(demo).toContain('"收官流·熄灯": ["收官流·封账", "收官流·熄灯", "收官流·灭灯"]');
    expect(demo).toContain('"稳压流·定盘": ["稳压流·锁墙", "稳压流·定盘", "稳压流·压底"]');
    expect(demo).toContain('if (chapterProfile?.featuredCombos?.length) return chapterProfile.featuredCombos;');
    expect(demo).toContain('...(chapterProfile?.rewardBias ?? [])');
    expect(demo).toContain('if (chapterProfile?.bossGoals?.length) goals.push(...chapterProfile.bossGoals.map((goal) => ({ ...goal })));');
    expect(demo).toContain("const ENDLESS_SPECIAL_EVENT_PHASE_BIAS = {");
    expect(demo).toContain("const ENDLESS_SPECIAL_EVENT_STEP_BIAS = [");
    expect(demo).toContain('7: ["tail-lantern", "west-tail-lock", "north-tail-break"]');
    expect(demo).toContain("const ENDLESS_REWARD_PHASE_BIAS = {");
    expect(demo).toContain("const ENDLESS_REWARD_STEP_BIAS = {");
    expect(demo).toContain("const MAINLINE_REWARD_ORDER_BIAS = {");
    expect(demo).toContain("const DAILY_REWARD_ORDER_BIAS = {");
    expect(demo).toContain("const ASCENSION_REWARD_LEVEL_BIAS = {");
    expect(demo).toContain('"daily-warden": {');
    expect(demo).toContain('title: "每日 Boss 变体"');
    expect(demo).toContain('rewardQuality: "今日"');
    expect(demo).toContain("function getDailyBossPack(levelIndex = model.levelIndex)");
    expect(demo).toContain("function getDailyBossTrialPhases(levelIndex = model.levelIndex)");
    expect(demo).toContain('if (isDailyMode() && isBossLevel(levelIndex)) return BOSS_TRIAL_VARIANTS["daily-warden"];');
    expect(demo).toContain('if (isDailyMode() && isBossLevel(levelIndex)) return getDailyBossTrialPhases(levelIndex);');
    expect(demo).toContain('if (isDailyMode() && getActiveBossGoals(model.levelIndex).length > 0) return "每日";');
    expect(demo).toContain("function getEndlessBossPack(levelIndex = model.levelIndex)");
    expect(demo).toContain("function getEndlessBossTrialPhases(levelIndex = model.levelIndex)");
    expect(demo).toContain("function getFinalBossPack(levelIndex = model.levelIndex)");
    expect(demo).toContain("function getFinalBossTrialPhases(levelIndex = model.levelIndex)");
    expect(demo).toContain("if (isEndlessMode() && isBossLevel(levelIndex)) return getEndlessBossTrialPhases(levelIndex);");
    expect(demo).toContain("if (isFriendDemoFinalBossLevel(levelIndex)) return getFinalBossTrialPhases(levelIndex);");
    expect(demo).toContain('title: `${chapterProfile?.label ?? `第 ${chapter} 章`} · ${theme}守层`');
    expect(demo).toContain('title: `${FRIEND_DEMO_FINAL_BOSS_TITLE} · ${archetype.label}`');
    expect(demo).toContain('const runArchetypeLabel = getRunArchetypeConfig(model.runArchetype).label;');
    expect(demo).toContain('focus: `${runArchetypeLabel} · ${finalBossPack?.focusLine ?? variant.focus}`');
    expect(demo).not.toContain('focus: `${model.preferredRoute || "当前路线"} · ${finalBossPack?.focusLine ?? variant.focus}`');
    expect(demo).toContain("const preferredRouteEvent = getPreferredRouteEventBias();");
    expect(demo).toContain("if (preferredRouteEvent) pool.unshift(preferredRouteEvent);");
    expect(demo).toContain("function getPreferredRouteEventBias()");
    expect(demo).not.toContain('if (preferredRoute.includes("信息流") || preferredRoute.includes("试锋")) pool.unshift(SPECIAL_EVENT_POOL.find((event) => event.id === "old-tile-box"));');
    expect(demo).not.toContain('if (preferredRoute.includes("道具流") || preferredRoute.includes("救场")) pool.unshift(SPECIAL_EVENT_POOL.find((event) => event.id === "old-sparrow"));');
    expect(demo).toContain('{ minChapter: 4, step: 1, eventIds: ["tail-lantern", "west-tail-lock", "west-throat-seal"] }');
    expect(demo).toContain('{ minChapter: 6, step: 3, eventIds: ["north-tail-break", "lantern-peek", "north-coal-burn"] }');
    expect(demo).toContain('{ minChapter: 7, step: 4, eventIds: ["west-tail-lock", "north-tail-break", "north-coal-burn"] }');
    expect(demo).toContain('6: ["gang_score_plus_25", "hu_coin_plus_15", "info_vision_plus_1"]');
    expect(demo).toContain('7: ["gang_score_plus_25", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(demo).toContain('8: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('4: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain("...(ENDLESS_REWARD_PHASE_BIAS[chapterProfile?.phase ?? 1] ?? [])");
    expect(demo).toContain("...(ENDLESS_REWARD_STEP_BIAS[chapterStep] ?? [])");
    expect(demo).toContain('rewardBias: ["gang_score_plus_25", "chi_tool_supply", "info_vision_plus_1", "hu_coin_plus_15"]');
    expect(demo).toContain('rewardBias: ["hu_coin_plus_15", "gang_score_plus_25", "tool_mix_supply", "discard_plus_1"]');
    expect(demo).toContain('rewardBias: ["hu_score_plus_18", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(demo).toContain('rewardBias: ["tool_mix_supply", "hu_coin_plus_15", "discard_plus_1"]');
    expect(demo).toContain('rewardBias: ["hu_coin_plus_15", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('rewardBias: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('13: ["info_vision_plus_1", "tool_mix_supply", "hu_coin_plus_15"]');
    expect(demo).toContain('16: ["hu_score_plus_18", "hu_coin_plus_15", "gang_score_plus_25"]');
    expect(demo).toContain('19: ["gang_score_plus_25", "hu_coin_plus_15", "tool_mix_supply"]');
    expect(demo).toContain('18: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('12: ["chi_tool_supply", "info_shuffle_plus_1", "hu_coin_plus_15"]');
    expect(demo).toContain('14: ["hu_coin_plus_15", "hu_score_plus_18", "gang_score_plus_25"]');
    expect(demo).toContain('16: ["hu_coin_plus_15", "info_shuffle_plus_1", "tool_mix_supply"]');
    expect(demo).toContain(`const DAILY_REWARD_ORDER_BIAS = {
        12: ["info_vision_plus_1", "info_shuffle_plus_1", "tool_mix_supply"],
        14: ["hu_coin_plus_15", "hu_score_plus_18", "gang_score_plus_25"],
        16: ["hu_coin_plus_15", "info_shuffle_plus_1", "tool_mix_supply"],
        18: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"],
        20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"],
      };`);
    expect(demo).toContain('14: ["hu_coin_plus_15", "tool_mix_supply", "info_shuffle_plus_1"]');
    expect(demo).toContain('16: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('18: ["hu_coin_plus_15", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain('20: ["hu_score_plus_18", "gang_score_plus_25", "tool_mix_supply"]');
    expect(demo).toContain("const mainlineLateRewardBias = !isAscensionMode()");
    expect(demo).toContain("getThresholdBiasChain(MAINLINE_REWARD_ORDER_BIAS, mainlineOrder)");
    expect(demo).toContain("const dailyLateRewardBias = getThresholdBiasChain(DAILY_REWARD_ORDER_BIAS, dailyOrder);");
    expect(demo).toContain("...getThresholdBiasChain(ASCENSION_REWARD_LEVEL_BIAS, levelIndex),");
    expect(demo).not.toContain("Object.entries(DAILY_REWARD_ORDER_BIAS).reduce");
    expect(demo).not.toContain("Object.entries(ASCENSION_REWARD_LEVEL_BIAS).reduce");
    expect(demo).toContain('filter((combo) => combo === "hu" || combo === "gang").slice(0, 1)');
    expect(demo).toContain("const normalizedPackBonusGoals = (pack.bonusGoals ?? []).flatMap((goal) => {");
    expect(demo).toContain('if (goal.type === "combo_count" && goal.combo !== "hu" && goal.combo !== "gang") return [];');
    expect(demo).toContain('if (goal.type === "combo_count" && goal.combo === "gang") {');
    expect(demo).toContain('return [{ ...goal, target: 1 }];');
    expect(demo).toContain("const chapterBossComboGoalCount = (chapterProfile?.bossGoals ?? []).filter((goal) => goal.type === \"combo_count\").length;");
    expect(demo).toContain("const shouldAddEndlessPengGoal = phase >= 4 && phase < 6 && chapterBossComboGoalCount < 2;");
    expect(demo).toContain("const endlessScoreTarget = 164 + chapter * 16;");
    expect(demo).toContain("if (shouldAddEndlessPengGoal) goals.splice(1, 0, { type: \"combo_count\", combo: \"peng\", target: 1 });");
    expect(demo).toContain("const LATE_ROUTE_REWARD_BIAS = {");
    expect(demo).toContain("function getPreferredRouteLateRewardBias(levelIndex = model.levelIndex)");
    expect(demo).toContain("function getLateRouteBiasForLabel(label, levelIndex = model.levelIndex)");
    expect(demo).toContain('model.runArchetype = RUN_ARCHETYPE_CONFIGS[requestedRunArchetype] ? requestedRunArchetype : "chi";');
    expect(demo).toContain("const archetypeRewardPool = getRunArchetypeRewardPool(levelIndex);");
    expect(demo).toContain("if (routeMasteryLevel <= 0 || !model.preferredRoute) return null;");
    expect(demo).toContain('if (model.preferredRoute.includes("河控")) return ["gang_score_plus_25"];');
    expect(demo).toContain('if (model.preferredRoute.includes("救场")) return ["shield_plus_1"];');
    expect(demo).not.toContain("const lateBias = routeMasteryLevel >= 2 ? getPreferredRouteLateRewardBias(levelIndex).slice(0, 1) : [];");
    expect(demo).not.toContain('if (model.preferredRoute.includes("河控")) return ["gang_score_plus_25", ...lateBias];');
    expect(demo).toContain('routeDirection: isAscensionMode() ? getAscensionBuildProfile()?.name ?? null : getRunArchetypeConfig(model.runArchetype).label,');
    expect(demo).toContain('if ((chapterProfile?.chapter ?? 0) < 4) return [];');
    expect(demo).toContain("if (dailyOrder < 12) return [];");
    expect(demo).toContain("if (levelIndex < 10) return [];");
    expect(demo).toContain("if (mainlineOrder < 13) return [];");
    expect(demo).toContain("if (routeMasteryLevel < 2) return [];");
  });

  it("ships the expected daily and progression hooks for the shell", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");
    const demo = readWebFile("public/games/hulebu-demo/index.html");

    expect(component).toContain("dailyStreak");
    expect(component).toContain("bestAscensionLevel");
    expect(component).toContain("specialEventReview");
    expect(component).toContain("routeDirection");
    expect(component).toContain("主线长度");
    expect(component).toContain("试炼关");
    expect(component).toContain("终章 Boss");
    expect(component).toContain("继续进度");
    expect(component).toContain("当前章节");
    expect(component).toContain("章节 Boss");
    expect(component).toContain("章节主题");
    expect(component).toContain("今日词缀");
    expect(component).toContain("今日奖励");
    expect(component).toContain("河道扩容");
    expect(component).toContain("开局铜钱");
    expect(component).toContain("看山预置");
    expect(component).toContain("偏好当前收益");
    expect(component).toContain("偏好下一步");
    expect(component).toContain("当前收益");
    expect(component).toContain("胡流会轻补");
    expect(component).toContain("信息流会轻补");
    expect(component).toContain("河控流会轻补");
    expect(component).toContain("道具流会轻补");
    expect(component).toContain("救场流会轻补");
    expect(component).toContain("继续补这条长期线");
    expect(component).toContain("当前装配");
    expect(component).toContain("能力图鉴");
    expect(component).toContain("直接开局，只看必要状态。");
    expect(component).not.toContain("主线分段导向");
    expect(component).not.toContain("无尽章节导向");
    expect(component).not.toContain("每日词缀导向");
    expect(component).not.toContain("节奏提醒");
    expect(component).not.toContain("优先追的奖励");
    expect(component).not.toContain("更容易撞到的事件");
    expect(component).not.toContain("这一轮先去哪");
    expect(component).not.toContain("后半程怎么收");
    expect(component).not.toContain("奖励倾向");
    expect(component).not.toContain("事件倾向");
    expect(component).not.toContain("模式建议");
    expect(component).not.toContain("收官读法");
    expect(component).not.toContain("本轮路线：");
    expect(component).not.toContain("今日词缀：等待今日开局");
    expect(component).not.toContain("今日奖励：等待今日结算");
    expect(component).not.toContain("章节 Boss · 每 5 层结一次压力");
    expect(component).not.toContain("<span>equippedAscensionLoadout</span>");
    expect(component).not.toContain("<span>unlockedAscensionPerks</span>");
    expect(demo).toContain("function getDailyStartBonus()");
    expect(demo).toContain("openerLabel");
    expect(demo).toContain("开局带 1 格河道和 1 层护符");
    expect(demo).toContain("function getSpecialEventTriggerKey(levelIndex)");
    expect(demo).toContain("function getSpecialEventTriggerPosition(levelIndex)");
    expect(demo).toContain("function isEndlessSpecialEventTriggerLayer(layer)");
    expect(demo).toContain("if (maybeShowSpecialEventBeforeLevel(model.levelIndex)) return;");
    expect(demo).toContain("const chapterIndex = Math.floor((layer - ENDLESS_START_LAYER) / 5);");
    expect(demo).toContain("chapterIndex >= 1 && chapterStep === 4");
    expect(demo).toContain("chapterIndex >= 3 && chapterStep === 1");
    expect(demo).toContain("const dailyLateEventBiasMap = {");
    expect(demo).toContain("const ascensionLateEventBiasMap = {");
    expect(demo).toContain('`daily:${model.run.dailySeed || "today"}:${order}`');
    expect(demo).toContain("const ENDLESS_SPECIAL_EVENT_PHASE_BIAS = {");
    expect(demo).toContain("const ENDLESS_SPECIAL_EVENT_STEP_BIAS = [");
    expect(demo).toContain('7: ["tail-lantern", "west-tail-lock", "north-tail-break"]');
    expect(demo).toContain('{ minChapter: 7, step: 4, eventIds: ["west-tail-lock", "north-tail-break", "north-coal-burn"] }');
    expect(demo).toContain("西风定口·封喉");
    expect(demo).toContain("北风封火·闷燃");
    expect(demo).toContain("west-throat-seal");
    expect(demo).toContain("north-coal-burn");
    expect(demo).toContain('12: ["east-guard-mouth", "old-tile-box"]');
    expect(demo).toContain('14: ["route-followup", "risk-double-down"]');
    expect(demo).toContain('16: ["south-wall-breathe", "seal-delayed"]');
    expect(demo).toContain('18: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(demo).toContain('20: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
    expect(demo).toContain('11: ["east-scout-pressure", "old-tile-box"]');
    expect(demo).toContain('17: ["tail-lantern", "west-tail-lock", "west-throat-seal"]');
    expect(demo).toContain('19: ["north-tail-break", "west-tail-lock", "north-coal-burn"]');
  });

  it("expands the codex with deeper endless, daily, upgrade, and route milestones", () => {
    const component = readWebFile("src/modules/games/hulebu/HulebuGamePage.tsx");

    expect(component).toContain('id: "endless-layer-40"');
    expect(component).toContain('title: "冲到 40 层"');
    expect(component).toContain('state.bestEndlessLayer >= 40');
    expect(component).toContain('id: "daily-streak-7"');
    expect(component).toContain('title: "连到 7 天"');
    expect(component).toContain("state.dailyStreak >= 7");
    expect(component).toContain('id: "upgrade-all-six"');
    expect(component).toContain('title: "六轴全开"');
    expect(component).toContain('id: "route-focus-mastered"');
    expect(component).toContain('title: "路线挂满"');
    expect(component).toContain('getRouteFocusMasteryLevel("hu", state.upgrades) >= 2');
    expect(component).toContain('getRouteFocusMasteryLevel("survive", state.upgrades) >= 2');
  });
});
